### ISSUE TITLE
NullPointerException when pop on Hystrix#list is called Hystrix#endCurrentThreadExecutingCommand

### ISSUE THREAD

**Issue by mzeijen** [Netflix/Hystrix#1012]
We sometimes get a warning logged of a NullPointer within the LinkedList of the Hystrix#list field when it's pop methods is called during the Hystrix#endCurrentThreadExecutingCommand execution. It can happen a couple of thousands of times an hour and sometimes almost never

I don't know when this happens and we can't reproduce it. Looks like a multi threading issue where there is some concurrent access on that linked list which causes the problem. 

We see this in Hystrix version 1.4.13 but the Hystrix code regarding this part seems the same in the current 1.4.21 version. Maybe this is already fixed but I can't find anything related in the issues.

Stacktrace:
```
java.lang.NullPointerException
	at java.util.LinkedList.remove(LinkedList.java:791)
	at java.util.LinkedList.removeFirst(LinkedList.java:134)
	at java.util.LinkedList.pop(LinkedList.java:601)
	at com.netflix.hystrix.Hystrix.endCurrentThreadExecutingCommand(Hystrix.java:134)
	at com.netflix.hystrix.Hystrix.access$000(Hystrix.java:32)
	at com.netflix.hystrix.Hystrix$2.call(Hystrix.java:121)
	at com.netflix.hystrix.AbstractCommand.handleThreadEnd(AbstractCommand.java:916)
	at com.netflix.hystrix.AbstractCommand$7.call(AbstractCommand.java:665)
	at rx.Observable$11.onCompleted(Observable.java:4309)
	at rx.internal.operators.OperatorDoOnEach$1.onCompleted(OperatorDoOnEach.java:46)
	at rx.internal.operators.OperatorDoOnEach$1.onCompleted(OperatorDoOnEach.java:53)
	at rx.internal.operators.OperatorOnErrorResumeNextViaFunction$1.onCompleted(OperatorOnErrorResumeNextViaFunction.java:64)
	at rx.internal.operators.OperatorDoOnEach$1.onCompleted(OperatorDoOnEach.java:53)
	at rx.internal.operators.OperatorDoOnEach$1.onCompleted(OperatorDoOnEach.java:53)
	at com.netflix.hystrix.AbstractCommand$HystrixObservableTimeoutOperator$3.onCompleted(AbstractCommand.java:1012)
	at rx.internal.operators.OperatorDoOnEach$1.onCompleted(OperatorDoOnEach.java:53)
	at rx.internal.operators.OperatorDoOnEach$1.onCompleted(OperatorDoOnEach.java:53)
	at com.netflix.hystrix.AbstractCommand$DeprecatedOnRunHookApplication$1.onCompleted(AbstractCommand.java:1481)
	at com.netflix.hystrix.AbstractCommand$ExecutionHookApplication$1.onCompleted(AbstractCommand.java:1379)
	at rx.internal.operators.OperatorMap$1.onCompleted(OperatorMap.java:44)
        at .... (we call the onCompleted here of the observable)
```

**Comment by mattrjacobs** [comment]
Thanks for the report, @mzeijen.  That does sounds like a concurrent-access problem.  I'll take a look

**Comment by mzeijen** [comment]
Great, thank you!

**Comment by mzeijen** [comment]
I just noticed we of course also see a similar problem when pushing the command key into the list:

```
java.lang.NullPointerException
	at java.util.LinkedList.addBefore(LinkedList.java:779)
	at java.util.LinkedList.addFirst(LinkedList.java:153)
	at java.util.LinkedList.push(LinkedList.java:586)
	at com.netflix.hystrix.Hystrix.startCurrentThreadExecutingCommand(Hystrix.java:113)
	at com.netflix.hystrix.AbstractCommand.getRunObservableDecoratedForMetricsAndErrorHandling(AbstractCommand.java:547)
	at com.netflix.hystrix.AbstractCommand.access$100(AbstractCommand.java:65)
	at com.netflix.hystrix.AbstractCommand$1.call(AbstractCommand.java:398)
	at com.netflix.hystrix.AbstractCommand$1.call(AbstractCommand.java:377)
	at rx.Observable$1.call(Observable.java:144)
	at rx.Observable$1.call(Observable.java:136)
	at rx.Observable$1.call(Observable.java:144)
	at rx.Observable$1.call(Observable.java:136)
	at rx.Observable$1.call(Observable.java:144)
	at rx.Observable$1.call(Observable.java:136)
	at rx.Observable.unsafeSubscribe(Observable.java:7531)
	at com.netflix.hystrix.AbstractCommand$ObservableCommand$1.call(AbstractCommand.java:1149)
	at com.netflix.hystrix.AbstractCommand$ObservableCommand$1.call(AbstractCommand.java:1145)
	at rx.Observable.subscribe(Observable.java:7621)
	at rx.Observable.subscribe(Observable.java:7490)
	at com.netflix.hystrix.AbstractCommand.observe(AbstractCommand.java:321)
	at com.netflix.hystrix.HystrixObservableCommand.observe(HystrixObservableCommand.java:35)
```

**Comment by mzeijen** [comment]
Important to note is that we are using our command with the semaphore isolation strategy.

**Comment by mattrjacobs** [comment]
Yeah, I can replicate this fairly easily.  This set of methods made more sense when a thread was executing one command at a time.  It's hard to imagine what this method should return in a Netty event loop, for example.  When a single thread is responsible for launching multiple commands, then a ThreadLocal no longer offers any sort of protection against concurrent access/modification to the list

I need to think about what I want to do with this functionality.  It seems hard to offer as a feature that works in any execution scenario, and doesn't seem especially valuable.

**Comment by mattrjacobs** [comment]
I've given this a bit of thought and here's where I'm at:

The work done by `AbstractCommand` is essentially done to support the `Hystrix.getCurrentThreadExecutingCommand` method.  This method can be called from anywhere to determine if a Hystrix command is running on that thread at the moment.  An example usage would be for a Hystrix command makes an HTTP call, and the HTTP network library uses `Hystrix.getCurrentThreadExecutingCommand` to map the network call to a Hystrix command.

This functionality should work fine when using with thread-isolation.  In that scenario, a thread can nest commands, but there's a single call chain represented by a thread.

When semaphore-isolation is used, there's no guarantee on how many call chains are running in a single caller thread.  A Netty event loop is the first thing that comes to mind.

I'm leaning toward marking this functionality as deprecated, and eventually removing it.  I don't think there's a way to make it work when semaphore isolation and `HystrixObservableCommand`s are used.  I think that any desired functionality that this method supplies could be emulated by supplying a custom `HystrixCommandExecutionHook`.  If this is the path taken, then I could issue a temporary fix to eliminate the NPEs by using a thread-safe data structure in the `Hystrix` class.  

Any thoughts from the community on the best path forward, given the above constraints?  Leaving it as-is is not an option, as NPEs during normal operation are not OK.

**Comment by mzeijen** [comment]
Deprecating and using a thread-safe data structure sounds like a good solution. 

We are now forced to disable logging for the Hystrix class because it is causing more then a million Nullpointer log messages per day now.

**Comment by mzeijen** [comment]
The fix should solve the issue (as is proven in the unit test).
