### ISSUE TITLE
CircuitBreaker issue where it never closes even after service instance is brought up

### ISSUE THREAD

**Issue by nmallya** [Netflix/Hystrix#1016]
I am facing a strange issue where an open circuit breaker doesn't seem to close even after the offending service (which was down) is brought back up.

Details:
In my test, I use Eureka and a Feign Client from my Controller to talk to a simple REST service that returns a canned string.When I bring down that REST service and hit the controller repeatedly, the circuit opens and fallback code executes properly

```
 @Autowired XYZAPIClient xyzAPIClient;
 @HystrixCommand(fallbackMethod="getFallbackStatus")
	public String getStatus(String x, String y) {
	 	System.out.println("Getting status...");
 		return xyzAPIClient.getStatus(x, y); // if i put this in a try catch, and debug when exception caught, subsequent requests start working 
	}
	
	public String getFallbackStatus(String x, String y) {
		System.out.println("Falling back on default data for status");
		return "XYZAPI is DOWN. This is a graceful fallback";
	}
```

When i bring up the service again, Eureka recognizes it as UP. However, no matter how long I wait (over 10 mins), every request tends to go to fallback mode. While I do see requests periodically making their way to the original method,  it always gets kicked back to the fallback

Another twist: When i put a try-catch  in the FeignClient call to the REST API and caught the exception, THEN onwards the requests started succeeding and the circuit was closed. Somehow the "time spent" during that debugging was triggering the recognition of the service instance coming up.

**Comment by mattrjacobs** [comment]
Circuit-breakers only return to fully-closed once they see a SUCCESS.  That lines up with the observation you made in the comment above - that adding a try-catch to `xyzClient.getStatus` causes the circuit to close.

The implication is that `xyzClient.getStatus` is not successful for some reason, and therefore the circuit is not closing, even though the service is UP in Eureka.  If you inspect the details of the caught exception, hopefully that will give you a clue.

**Comment by nmallya** [comment]
Thank you mattrjacobs. 
What i see happening: 
when i bring up the XYZService instance, it does not seem to be detected even though it is up in Eureka (even after several minutes). Since I am using FeignClient annotation, I am wondering if Ribbon is not getting refreshed somehow. (I have not configured Ribbon explicitly). Please let me know if there is a way where once the instance comes up, I can "force" Ribbon/Feign/Hystrix to recognize this. 

The stack trace:
com.netflix.hystrix.exception.HystrixRuntimeException: getStatus short-circuited and no fallback available.
Falling back on default data for status
	at com.netflix.hystrix.AbstractCommand$16.call(AbstractCommand.java:801)
	at com.netflix.hystrix.AbstractCommand$16.call(AbstractCommand.java:785)
	at rx.internal.operators.OperatorOnErrorResumeNextViaFunction$1.onError(OperatorOnErrorResumeNextViaFunction.java:77)
	at rx.internal.operators.OperatorDoOnEach$1.onError(OperatorDoOnEach.java:70)
	at rx.internal.operators.OperatorDoOnEach$1.onError(OperatorDoOnEach.java:70)
	at rx.internal.operators.OperatorDoOnEach$1.onError(OperatorDoOnEach.java:70)
	at com.netflix.hystrix.AbstractCommand$DeprecatedOnFallbackHookApplication$1.onError(AbstractCommand.java:1514)
	at com.netflix.hystrix.AbstractCommand$FallbackHookApplication$1.onError(AbstractCommand.java:1404)
	at com.netflix.hystrix.HystrixCommand$2.call(HystrixCommand.java:314)
	at com.netflix.hystrix.HystrixCommand$2.call(HystrixCommand.java:306)
	at rx.Observable$1.call(Observable.java:144)
	at rx.Observable$1.call(Observable.java:136)
	at rx.Observable$1.call(Observable.java:144)
	at rx.Observable$1.call(Observable.java:136)
	at rx.Observable$1.call(Observable.java:144)
	at rx.Observable$1.call(Observable.java:136)
	at rx.Observable$1.call(Observable.java:144)
	at rx.Observable$1.call(Observable.java:136)
	at rx.Observable$1.call(Observable.java:144)
	at rx.Observable$1.call(Observable.java:136)
	at rx.Observable$1.call(Observable.java:144)
	at rx.Observable$1.call(Observable.java:136)
	at rx.Observable$1.call(Observable.java:144)
	at rx.Observable$1.call(Observable.java:136)
	at rx.Observable$1.call(Observable.java:144)
	at rx.Observable$1.call(Observable.java:136)
	at rx.Observable$1.call(Observable.java:144)
	at rx.Observable$1.call(Observable.java:136)
	at rx.Observable$1.call(Observable.java:144)
	at rx.Observable$1.call(Observable.java:136)
	at rx.Observable$1.call(Observable.java:144)
	at rx.Observable$1.call(Observable.java:136)
	at rx.Observable.unsafeSubscribe(Observable.java:7531)
	at com.netflix.hystrix.AbstractCommand$1.call(AbstractCommand.java:413)
	at com.netflix.hystrix.AbstractCommand$1.call(AbstractCommand.java:363)
	at rx.Observable$1.call(Observable.java:144)
	at rx.Observable$1.call(Observable.java:136)
	at rx.Observable$1.call(Observable.java:144)
	at rx.Observable$1.call(Observable.java:136)
	at rx.Observable$1.call(Observable.java:144)
	at rx.Observable$1.call(Observable.java:136)
	at rx.Observable.unsafeSubscribe(Observable.java:7531)
	at com.netflix.hystrix.AbstractCommand$ObservableCommand$1.call(AbstractCommand.java:1133)
	at com.netflix.hystrix.AbstractCommand$ObservableCommand$1.call(AbstractCommand.java:1129)
	at rx.Observable$1.call(Observable.java:144)
	at rx.Observable$1.call(Observable.java:136)
	at rx.Observable.subscribe(Observable.java:7621)
	at rx.internal.operators.BlockingOperatorToFuture.toFuture(BlockingOperatorToFuture.java:57)
	at rx.observables.BlockingObservable.toFuture(BlockingObservable.java:410)
	at com.netflix.hystrix.HystrixCommand.queue(HystrixCommand.java:379)
	at com.netflix.hystrix.HystrixCommand.execute(HystrixCommand.java:335)
	at feign.hystrix.HystrixInvocationHandler.invoke(HystrixInvocationHandler.java:66)
	at com.sun.proxy.$Proxy91.getStatus(Unknown Source)
	at com.example.domain.HystrixFallbackService.getStatus(HystrixFallbackService.java:28)
	at sun.reflect.GeneratedMethodAccessor101.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.netflix.hystrix.contrib.javanica.command.MethodExecutionAction.execute(MethodExecutionAction.java:116)
	at com.netflix.hystrix.contrib.javanica.command.MethodExecutionAction.executeWithArgs(MethodExecutionAction.java:89)
	at com.netflix.hystrix.contrib.javanica.command.MethodExecutionAction.execute(MethodExecutionAction.java:78)
	at com.netflix.hystrix.contrib.javanica.command.GenericCommand$1.execute(GenericCommand.java:47)
	at com.netflix.hystrix.contrib.javanica.command.AbstractHystrixCommand.process(AbstractHystrixCommand.java:158)
	at com.netflix.hystrix.contrib.javanica.command.GenericCommand.run(GenericCommand.java:44)
	at com.netflix.hystrix.HystrixCommand$1.call(HystrixCommand.java:294)
	at com.netflix.hystrix.HystrixCommand$1.call(HystrixCommand.java:289)
	at rx.Observable$1.call(Observable.java:144)
	at rx.Observable$1.call(Observable.java:136)
	at rx.Observable$1.call(Observable.java:144)
	at rx.Observable$1.call(Observable.java:136)
	at rx.Observable$1.call(Observable.java:144)
	at rx.Observable$1.call(Observable.java:136)
	at rx.Observable.unsafeSubscribe(Observable.java:7531)
	at com.netflix.hystrix.AbstractCommand$5.call(AbstractCommand.java:520)
	at com.netflix.hystrix.AbstractCommand$5.call(AbstractCommand.java:495)
	at rx.Observable.unsafeSubscribe(Observable.java:7531)
	at rx.internal.operators.OperatorSubscribeOn$1$1.call(OperatorSubscribeOn.java:62)
	at com.netflix.hystrix.strategy.concurrency.HystrixContexSchedulerAction$1.call(HystrixContexSchedulerAction.java:56)
	at com.netflix.hystrix.strategy.concurrency.HystrixContexSchedulerAction$1.call(HystrixContexSchedulerAction.java:47)
	at com.netflix.hystrix.strategy.concurrency.HystrixContexSchedulerAction.call(HystrixContexSchedulerAction.java:69)
	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: Hystrix circuit short-circuited and is OPEN
	... 52 more

**Comment by mattrjacobs** [comment]
Hystrix is separate from Ribbon, and doesn't handle any networking.  Can you try getting help from the Ribbon developers?  I'm not an expert on that code, so you'll likely get a better answer that way.

**Comment by nmallya** [comment]
Will do, thanks again
