### ISSUE TITLE
Problem with java rx version 1.1.1

### ISSUE THREAD

**Issue by javier-garcia-piksel** [Netflix/Hystrix#1104]
With rx version 1.1.1 the release of fallback semaphore is never executed
Using java rx version 1.1.1 this method of AbstractCommand is never executed:

```
fallbackExecutionChain =  fallbackExecutionChain
                            .lift(new FallbackHookApplication(_cmd))
                            .lift(new DeprecatedOnFallbackHookApplication(_cmd))
                            .doOnTerminate(new Action0() {

                                @Override
                                public void call() {
                                    **_fallbackSemaphore.release();_**
                                }
                            });
```

**Comment by mattrjacobs** [comment]
I can't reproduce your problem.  When I add a println to the fallback semaphore release here: https://github.com/mattrjacobs/Hystrix/commit/61228ab04ef376d3fa8070ebe0a665febe1d3385

and run the test `HystrixCommandTest.testFallbackSemaphore`, I get the following output:

```
metrics : KEY_ONE : HealthCounts[0 / 0 : 0%]
Releasing the fallback semaphore!
c2 start: 1456337939485
metrics : KEY_ONE : HealthCounts[0 / 0 : 0%]
c2 after queue: 1456337939488
c3 start: 1456337939543
metrics : KEY_ONE : HealthCounts[0 / 0 : 0%]
c3 after queue: 1456337939545
java.util.concurrent.ExecutionException: Observable onError
	at rx.internal.operators.BlockingOperatorToFuture$2.getValue(BlockingOperatorToFuture.java:124)
	at rx.internal.operators.BlockingOperatorToFuture$2.get(BlockingOperatorToFuture.java:108)
	at com.netflix.hystrix.HystrixCommandTest.testFallbackSemaphore(HystrixCommandTest.java:1278)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:45)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:42)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:28)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:30)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:263)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:68)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:47)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:157)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:78)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:212)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:68)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
Caused by: com.netflix.hystrix.exception.HystrixRuntimeException: TestSemaphoreCommandWithSlowFallback fallback execution rejected.
	at com.netflix.hystrix.AbstractCommand.getFallbackOrThrowException(AbstractCommand.java:768)
	at com.netflix.hystrix.AbstractCommand.access$200(AbstractCommand.java:59)
	at com.netflix.hystrix.AbstractCommand$9.call(AbstractCommand.java:642)
	at com.netflix.hystrix.AbstractCommand$9.call(AbstractCommand.java:580)
	at rx.internal.operators.OperatorOnErrorResumeNextViaFunction$4.onError(OperatorOnErrorResumeNextViaFunction.java:139)
	at rx.internal.operators.OperatorDoOnEach$1.onError(OperatorDoOnEach.java:71)
	at rx.internal.operators.OperatorDoOnEach$1.onError(OperatorDoOnEach.java:71)
	at com.netflix.hystrix.AbstractCommand$HystrixObservableTimeoutOperator$3.onError(AbstractCommand.java:1008)
	at rx.internal.operators.OperatorDoOnEach$1.onError(OperatorDoOnEach.java:71)
	at rx.internal.operators.OperatorSubscribeOn$1$1.onError(OperatorSubscribeOn.java:59)
	at rx.internal.operators.OperatorDoOnEach$1.onError(OperatorDoOnEach.java:71)
	at com.netflix.hystrix.AbstractCommand$DeprecatedOnRunHookApplication$1.onError(AbstractCommand.java:1456)
	at com.netflix.hystrix.AbstractCommand$ExecutionHookApplication$1.onError(AbstractCommand.java:1352)
	at com.netflix.hystrix.HystrixCommand$1.call(HystrixCommand.java:296)
	at com.netflix.hystrix.HystrixCommand$1.call(HystrixCommand.java:288)
	at rx.Observable$2.call(Observable.java:162)
	at rx.Observable$2.call(Observable.java:154)
	at rx.Observable$2.call(Observable.java:162)
	at rx.Observable$2.call(Observable.java:154)
	at rx.Observable$2.call(Observable.java:162)
	at rx.Observable$2.call(Observable.java:154)
	at rx.Observable.unsafeSubscribe(Observable.java:8314)
	at com.netflix.hystrix.AbstractCommand$5.call(AbstractCommand.java:521)
	at com.netflix.hystrix.AbstractCommand$5.call(AbstractCommand.java:497)
	at rx.Observable.unsafeSubscribe(Observable.java:8314)
	at rx.internal.operators.OperatorSubscribeOn$1.call(OperatorSubscribeOn.java:94)
	at com.netflix.hystrix.strategy.concurrency.HystrixContexSchedulerAction$1.call(HystrixContexSchedulerAction.java:56)
	at com.netflix.hystrix.strategy.concurrency.HystrixContexSchedulerAction$1.call(HystrixContexSchedulerAction.java:47)
	at com.netflix.hystrix.strategy.concurrency.HystrixContexSchedulerAction.call(HystrixContexSchedulerAction.java:69)
	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:439)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
	at java.lang.Thread.run(Thread.java:695)
Releasing the fallback semaphore!

Process finished with exit code 0
```

**Comment by javier-garcia-piksel** [comment]
Hi Matt

I'm using a HystrixObservableCommand and I'm returning this in the fallback:

@Override
    protected Observable<List<Tweet>> resumeWithFallback() {
        return Observable.just(null);
    }

Doing that with java rx 1.1.1 the semaphore is never released


2016-02-24 18:23 GMT+00:00 Matt Jacobs <notifications@github.com>:

**Comment by mattrjacobs** [comment]
I believe handling of nulls might have changed in RxJava 1.1.1.  One quick solution to your problem should be to switch to return an empty list instead of null.  If that's not OK for your problem, can you open an issue against RxJava and ask there?

**Comment by javier-garcia-piksel** [comment]
Ok, i will try to use a empty list instead null.
I will let you know if using that solves the issue

2016-03-03 18:58 GMT+00:00 Matt Jacobs <notifications@github.com>:

**Comment by mattrjacobs** [comment]
Closing due to inactivity.  Please re-open if there's more to discuss
