### ISSUE TITLE
NullPointerException in HystrixInvocationHandler when calling hashCode, equals or toString of proxy

### ISSUE THREAD

**Issue by mpegram3rd** [Netflix/Hystrix#1178]
This issue is actually raised over on the Feign Issues board (see: [https://github.com/Netflix/feign/issues/332](https://github.com/Netflix/feign/issues/332) ), but really looks to be more of a Hystrix side problem.  

The problem occurs when using Feign proxies because they lack a hashCode/equals/toString().  Instead of checking for the presence of a method, HystrixInvocationHandler just blindly calls "invoke()" resulting in a NullPointerException.  See sample stacktrace below:
Destroy method on bean with name 'myFeignClient' threw an exception
com.netflix.hystrix.exception.HystrixRuntimeException: hashCode failed and no fallback available.
	at com.netflix.hystrix.AbstractCommand$16.call(AbstractCommand.java:811) ~[hystrix-core-1.4.14.jar:1.4.14]
	at com.netflix.hystrix.AbstractCommand$16.call(AbstractCommand.java:798) ~[hystrix-core-1.4.14.jar:1.4.14]
	at rx.internal.operators.OperatorOnErrorResumeNextViaFunction$1.onError(OperatorOnErrorResumeNextViaFunction.java:99) ~[rxjava-1.0.13.jar:1.0.13]
	at rx.internal.operators.OperatorDoOnEach$1.onError(OperatorDoOnEach.java:70) ~[rxjava-1.0.13.jar:1.0.13]
	at rx.internal.operators.OperatorDoOnEach$1.onError(OperatorDoOnEach.java:70) ~[rxjava-1.0.13.jar:1.0.13]
	at rx.internal.operators.OperatorDoOnEach$1.onError(OperatorDoOnEach.java:70) ~[rxjava-1.0.13.jar:1.0.13]
	at com.netflix.hystrix.AbstractCommand$DeprecatedOnFallbackHookApplication$1.onError(AbstractCommand.java:1530) ~[hystrix-core-1.4.14.jar:1.4.14]
	at com.netflix.hystrix.AbstractCommand$FallbackHookApplication$1.onError(AbstractCommand.java:1420) ~[hystrix-core-1.4.14.jar:1.4.14]
	at com.netflix.hystrix.HystrixCommand$2.call(HystrixCommand.java:314) ~[hystrix-core-1.4.14.jar:1.4.14]
	at com.netflix.hystrix.HystrixCommand$2.call(HystrixCommand.java:306) ~[hystrix-core-1.4.14.jar:1.4.14]
	at rx.Observable$1.call(Observable.java:145) ~[rxjava-1.0.13.jar:1.0.13]
	at rx.Observable$1.call(Observable.java:137) ~[rxjava-1.0.13.jar:1.0.13]
	at rx.Observable$1.call(Observable.java:145) ~[rxjava-1.0.13.jar:1.0.13]
	at rx.Observable$1.call(Observable.java:137) ~[rxjava-1.0.13.jar:1.0.13]
	at rx.Observable$1.call(Observable.java:145) ~[rxjava-1.0.13.jar:1.0.13]
	at rx.Observable$1.call(Observable.java:137) ~[rxjava-1.0.13.jar:1.0.13]
	at rx.Observable$1.call(Observable.java:145) ~[rxjava-1.0.13.jar:1.0.13]
	at rx.Observable$1.call(Observable.java:137) ~[rxjava-1.0.13.jar:1.0.13]
	at rx.Observable$1.call(Observable.java:145) ~[rxjava-1.0.13.jar:1.0.13]
	at rx.Observable$1.call(Observable.java:137) ~[rxjava-1.0.13.jar:1.0.13]
	at rx.Observable$1.call(Observable.java:145) ~[rxjava-1.0.13.jar:1.0.13]
	at rx.Observable$1.call(Observable.java:137) ~[rxjava-1.0.13.jar:1.0.13]
	at rx.Observable$1.call(Observable.java:145) ~[rxjava-1.0.13.jar:1.0.13]
	at rx.Observable$1.call(Observable.java:137) ~[rxjava-1.0.13.jar:1.0.13]
	at rx.Observable$1.call(Observable.java:145) ~[rxjava-1.0.13.jar:1.0.13]
	at rx.Observable$1.call(Observable.java:137) ~[rxjava-1.0.13.jar:1.0.13]
	at rx.Observable$1.call(Observable.java:145) ~[rxjava-1.0.13.jar:1.0.13]
	at rx.Observable$1.call(Observable.java:137) ~[rxjava-1.0.13.jar:1.0.13]
	at rx.Observable$1.call(Observable.java:145) ~[rxjava-1.0.13.jar:1.0.13]
	at rx.Observable$1.call(Observable.java:137) ~[rxjava-1.0.13.jar:1.0.13]
	at rx.Observable.unsafeSubscribe(Observable.java:7713) ~[rxjava-1.0.13.jar:1.0.13]
	at rx.internal.operators.OperatorOnErrorResumeNextViaFunction$1.onError(OperatorOnErrorResumeNextViaFunction.java:100) ~[rxjava-1.0.13.jar:1.0.13]
	at rx.internal.operators.OperatorDoOnEach$1.onError(OperatorDoOnEach.java:70) ~[rxjava-1.0.13.jar:1.0.13]
	at rx.internal.operators.OperatorDoOnEach$1.onError(OperatorDoOnEach.java:70) ~[rxjava-1.0.13.jar:1.0.13]
	at com.netflix.hystrix.AbstractCommand$HystrixObservableTimeoutOperator$3.onError(AbstractCommand.java:1021) ~[hystrix-core-1.4.14.jar:1.4.14]
	at rx.internal.operators.OperatorDoOnEach$1.onError(OperatorDoOnEach.java:70) ~[rxjava-1.0.13.jar:1.0.13]
	at rx.internal.operators.OperatorSubscribeOn$1$1$1.onError(OperatorSubscribeOn.java:71) ~[rxjava-1.0.13.jar:1.0.13]
	at rx.internal.operators.OperatorDoOnEach$1.onError(OperatorDoOnEach.java:70) ~[rxjava-1.0.13.jar:1.0.13]
	at com.netflix.hystrix.AbstractCommand$DeprecatedOnRunHookApplication$1.onError(AbstractCommand.java:1489) ~[hystrix-core-1.4.14.jar:1.4.14]
	at com.netflix.hystrix.AbstractCommand$ExecutionHookApplication$1.onError(AbstractCommand.java:1385) ~[hystrix-core-1.4.14.jar:1.4.14]
	at com.netflix.hystrix.HystrixCommand$1.call(HystrixCommand.java:297) ~[hystrix-core-1.4.14.jar:1.4.14]
	at com.netflix.hystrix.HystrixCommand$1.call(HystrixCommand.java:289) ~[hystrix-core-1.4.14.jar:1.4.14]
	at rx.Observable$1.call(Observable.java:145) ~[rxjava-1.0.13.jar:1.0.13]
	at rx.Observable$1.call(Observable.java:137) ~[rxjava-1.0.13.jar:1.0.13]
	at rx.Observable$1.call(Observable.java:145) ~[rxjava-1.0.13.jar:1.0.13]
	at rx.Observable$1.call(Observable.java:137) ~[rxjava-1.0.13.jar:1.0.13]
	at rx.Observable$1.call(Observable.java:145) ~[rxjava-1.0.13.jar:1.0.13]
	at rx.Observable$1.call(Observable.java:137) ~[rxjava-1.0.13.jar:1.0.13]
	at rx.Observable.unsafeSubscribe(Observable.java:7713) ~[rxjava-1.0.13.jar:1.0.13]
	at com.netflix.hystrix.AbstractCommand$5.call(AbstractCommand.java:534) ~[hystrix-core-1.4.14.jar:1.4.14]
	at com.netflix.hystrix.AbstractCommand$5.call(AbstractCommand.java:509) ~[hystrix-core-1.4.14.jar:1.4.14]
	at rx.Observable.unsafeSubscribe(Observable.java:7713) ~[rxjava-1.0.13.jar:1.0.13]
	at rx.internal.operators.OperatorSubscribeOn$1$1.call(OperatorSubscribeOn.java:62) ~[rxjava-1.0.13.jar:1.0.13]
	at com.netflix.hystrix.strategy.concurrency.HystrixContexSchedulerAction$1.call(HystrixContexSchedulerAction.java:56) ~[hystrix-core-1.4.14.jar:1.4.14]
	at com.netflix.hystrix.strategy.concurrency.HystrixContexSchedulerAction$1.call(HystrixContexSchedulerAction.java:47) ~[hystrix-core-1.4.14.jar:1.4.14]
	at com.netflix.hystrix.strategy.concurrency.HystrixContexSchedulerAction.call(HystrixContexSchedulerAction.java:69) ~[hystrix-core-1.4.14.jar:1.4.14]
	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55) ~[rxjava-1.0.13.jar:1.0.13]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) ~[na:1.7.0_79]
	at java.util.concurrent.FutureTask.run(FutureTask.java:262) ~[na:1.7.0_79]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) ~[na:1.7.0_79]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) ~[na:1.7.0_79]
	at java.lang.Thread.run(Thread.java:745) ~[na:1.7.0_79]
Caused by: java.lang.NullPointerException: null
	at feign.hystrix.HystrixInvocationHandler$1.run(HystrixInvocationHandler.java:54) ~[feign-hystrix-8.12.1.jar:8.12.1]
	at com.netflix.hystrix.HystrixCommand$1.call(HystrixCommand.java:294) ~[hystrix-core-1.4.14.jar:1.4.14]
	... 21 common frames omitted

**Comment by mattrjacobs** [comment]
I don't think there's anything to do within Hystrix.  See https://github.com/Netflix/feign/issues/332#issuecomment-212443908
