### ISSUE TITLE
Getting fallback execution rejected exception some times in HystrixObservableCommand.

### ISSUE THREAD

**Issue by ankit8051** [Netflix/Hystrix#1230]
Hi Team,

We are using Hystrix in our application. We have HystrixObservaleCommand on service layer. When i start the application and access one hystrix command it will work fine, after some time we are getting below exception.

```
com.netflix.hystrix.exception.HystrixRuntimeException: getTicketsAsync fallback execution rejected.
        at com.netflix.hystrix.AbstractCommand.getFallbackOrThrowException(AbstractCommand.java:764) ~[hystrix-core-1.4.21.jar:1.4.21]
        at com.netflix.hystrix.AbstractCommand.access$300(AbstractCommand.java:64) ~[hystrix-core-1.4.21.jar:1.4.21]
        at com.netflix.hystrix.AbstractCommand$1.call(AbstractCommand.java:403) ~[hystrix-core-1.4.21.jar:1.4.21]
        at com.netflix.hystrix.AbstractCommand$1.call(AbstractCommand.java:363) ~[hystrix-core-1.4.21.jar:1.4.21]
        at rx.Observable$2.call(Observable.java:162) ~[rxjava-1.0.14.jar:1.0.14]
        at rx.Observable$2.call(Observable.java:154) ~[rxjava-1.0.14.jar:1.0.14]
        at rx.Observable$2.call(Observable.java:162) ~[rxjava-1.0.14.jar:1.0.14]
        at rx.Observable$2.call(Observable.java:154) ~[rxjava-1.0.14.jar:1.0.14]
        at rx.Observable$2.call(Observable.java:162) ~[rxjava-1.0.14.jar:1.0.14]
        at rx.Observable$2.call(Observable.java:154) ~[rxjava-1.0.14.jar:1.0.14]
        at rx.Observable.unsafeSubscribe(Observable.java:7710) ~[rxjava-1.0.14.jar:1.0.14]
```
I have set bellow property for the hystrix command.

```
hystrix.command.getTicketsAsync.execution.isolation.semaphore.maxConcurrentRequests=50
hystrix.command.getTicketsAsync.fallback.isolation.semaphore.maxConcurrentRequests=50
```
When, i start the application it is working fine and proccess some requests perfectly. But after some time will get above exception. I am not getting why hystrix is giving this error even if i am proccessing only one request.

Thanks in advance.

**Comment by mukteshkrmishra** [comment]
Try increasing the service timeout.

Sent from my iPhone

On Jun 1, 2016, at 7:42 AM, ankit8051 <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Team,

We are using Hystrix in our application. We have HystrixObservaleCommand on service layer. When i start the application and access one hystrix command it will work fine, after some time we are getting below exception.

com.netflix.hystrix.exception.HystrixRuntimeException: getTicketsAsync fallback execution rejected.
        at com.netflix.hystrix.AbstractCommand.getFallbackOrThrowException(AbstractCommand.java:764) ~[hystrix-core-1.4.21.jar:1.4.21]
        at com.netflix.hystrix.AbstractCommand.access$300(AbstractCommand.java:64) ~[hystrix-core-1.4.21.jar:1.4.21]
        at com.netflix.hystrix.AbstractCommand$1.call(AbstractCommand.java:403) ~[hystrix-core-1.4.21.jar:1.4.21]
        at com.netflix.hystrix.AbstractCommand$1.call(AbstractCommand.java:363) ~[hystrix-core-1.4.21.jar:1.4.21]
        at rx.Observable$2.call(Observable.java:162) ~[rxjava-1.0.14.jar:1.0.14]
        at rx.Observable$2.call(Observable.java:154) ~[rxjava-1.0.14.jar:1.0.14]
        at rx.Observable$2.call(Observable.java:162) ~[rxjava-1.0.14.jar:1.0.14]
        at rx.Observable$2.call(Observable.java:154) ~[rxjava-1.0.14.jar:1.0.14]
        at rx.Observable$2.call(Observable.java:162) ~[rxjava-1.0.14.jar:1.0.14]
        at rx.Observable$2.call(Observable.java:154) ~[rxjava-1.0.14.jar:1.0.14]
        at rx.Observable.unsafeSubscribe(Observable.java:7710) ~[rxjava-1.0.14.jar:1.0.14]


I have set bellow property for the hystrix command.

hystrix.command.getTicketsAsync.execution.isolation.semaphore.maxConcurrentRequests=50
hystrix.command.getTicketsAsync.fallback.isolation.semaphore.maxConcurrentRequests=50


When, i start the application it is working fine and proccess some requests perfectly. But after some time will get above exception. I am not getting why hystrix is giving this error even if i am proccessing only one request.

Thanks in advance.

-

**Comment by mattrjacobs** [comment]
I don't think timeouts are related.  This problem is specific to fallback semaphores being acquired and never released.

This sounds like a bug which got fixed in 1.5.3.  See #1204 for some more details.  Can you try upgrading to that release to see if that solves your issue?

**Comment by ankit8051** [comment]
Thanks, Matt,

Thanks for your help. This new version hystrix jar worked for me. Now there are no any hystrix command  execution rejections.

**Comment by mattrjacobs** [comment]
Excellent- thanks for the confirmation.  We've started using HystrixObservableCommands much more, and ran into this issue as well
