### ISSUE TITLE
Thread interruption on timeout doesn't work (Testet with Hystrix 1.5.2 and 1.5.3)

### ISSUE THREAD

**Issue by carlmoser** [Netflix/Hystrix#1240]
i'm currently testing a command against a service that will never answer. This results in a thread pool with all threads active. In the thread dump I can see, that all these threads are stuck at "java.net.SocketInputStream.socketRead0".

I don't have any additional configuration in my project. That means the default values for "execution.isolation.thread.timeoutInMilliseconds", "execution.timeout.enabled" and "execution.isolation.thread.interruptOnTimeout" should result in interrupted threads after 1 second. but it doesn't work.

Hystrix is also unable to provide metrics about these thread pool. Spring's actuator endpoint "/metrics" contains no information about it and the Hystrix Stream / Hystrix dashboard also hasn't any information about this thread pool.

**Comment by mattrjacobs** [comment]
For thread interruption, Hystrix can't guarantee that the interruption actually happens.  Like all other code that runs on the JVM, you can only throw an `InterruptedException`, you can't force the wrapped code to catch it.  This is one of the reasons that Hystrix exists - we would much rather that a Hystrix thread gets stuck in this state than an application thread.

For the metrics issue, it's hard to debug your issue with this info.  If you add some breakpoints/printlns, you should be able to loop over the HystrixThreadPoolMetrics.getInstances values and see what instances of metrics are in your code.  You should also be able to take a thread dump and see what threads are actually getting setup.  Those may help you understand more about what's happening.

**Comment by demaniak** [comment]
@carlmoser - a question: when this happens, is the circuit breaker then perhaps stuck in an open state? I am hunting a problem where a specific circuit breaker trips (goes OPEN) and then stays open (as far as I could test this persists until I restart the container).

This circuit breaker in question is protecting a remote resource that may respond very slowly (or infrequently, but often enough might just hang or throw a socket exception).

Currently I have increased this circuit breaker's thread pool to a core size that I consider insanely large (60), and I'm monitoring it - this is how I noticed a slowly climbing "active" count (for the thread pool), that so far shows no sign of going down again. I am waiting to see if my symptoms kick in when the active count == core size.

**Comment by mattrjacobs** [comment]
@demaniak Circuit breakers only observe the flow of outcomes (Success/Failure/Timeout/etc).  The only way that circuit breakers remain open is:

1) They trip in the first place by reaching the minimum volume threshold and minimum error threshold
2) A subsequent attempt on that circuit does not succeed.

By default, after 5 seconds of the circuit being open, 1 single command is attempted.  If it succeeds, the circuit goes back to CLOSED and is subject to re-opening as above.  If it fails, it stays OPEN for another 5 seconds.

Can you check what's happening on requests through your circuit breaker after it's already been OPENed?

**Comment by demaniak** [comment]
Thanks for the reply @mattrjacobs .

I agree completely with all the theory you mention. 

So in order to get to the bottom of this, I have dropped the log levels to DEBUG to see if anything "obvious" jumps out.
After that  I started watching the Hystrix dashaboard, and noticed the active thread count slowly climbing.
And now I have hit the issue again: the circuit breaker is open (and is STAYING open), and the active thread count == pool size.

I have trawled through the (very noisy) logs as it stands, but nothing springs out - in fact it is suspiciously devoid of any hystrix loggers. All I can say for certain is that the fallback methods get called immediately when we attempt to call the `@HystrixCommand` annotated methods (for that specific thread pool).

Any specific logback config I can add to force more info out of the circuit breaker libs?

Thanks in advance.

PS: I am not sure if my problem actually relates to this particular issue (but it is the closest I could find after a lot of searching), should I perhaps rather open a new issue?

**Comment by demaniak** [comment]
Ok, I have manged to duplicate this situation on my local machine with a core thread size of 5.

So, first of all, I noticed that every now and then, I would get a SocketException when contacting the remote service.

So once I hit this persistent OPEN state on the CB, I poked a round with jvisualvm a bit, and after installing he "Thread Inspector"  plugin for jvisualvm, I could observe this stack trace in the relevant hystrix thread pool threads (after they got stuck in the active state):
```
java.lang.Thread.State: RUNNABLE
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:170)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at sun.security.ssl.InputRecord.readFully(InputRecord.java:465)
	at sun.security.ssl.InputRecord.read(InputRecord.java:503)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:973)
	- locked <beec12d> (a java.lang.Object)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1375)
	- locked <72c6dcee> (a java.lang.Object)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1403)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1387)
	at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:153)
	at org.springframework.http.client.SimpleBufferingClientHttpRequest.executeInternal(SimpleBufferingClientHttpRequest.java:80)
	at org.springframework.http.client.AbstractBufferingClientHttpRequest.executeInternal(AbstractBufferingClientHttpRequest.java:48)
	at org.springframework.http.client.AbstractClientHttpRequest.execute(AbstractClientHttpRequest.java:53)
	at org.springframework.http.client.InterceptingClientHttpRequest$InterceptingRequestExecution.execute(InterceptingClientHttpRequest.java:93)
	at org.springframework.cloud.netflix.metrics.MetricsClientHttpRequestInterceptor.intercept(MetricsClientHttpRequestInterceptor.java:65)
	at org.springframework.http.client.InterceptingClientHttpRequest$InterceptingRequestExecution.execute(InterceptingClientHttpRequest.java:85)
	at org.springframework.http.client.InterceptingClientHttpRequest.executeInternal(InterceptingClientHttpRequest.java:69)
	at org.springframework.http.client.AbstractBufferingClientHttpRequest.executeInternal(AbstractBufferingClientHttpRequest.java:48)
	at org.springframework.http.client.AbstractClientHttpRequest.execute(AbstractClientHttpRequest.java:53)
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:596)
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:557)
	at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:503)
	at org.springframework.web.client.RestTemplate$$FastClassBySpringCGLIB$$aa4e9ed0.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:720)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:85)
	at org.springframework.cloud.netflix.metrics.RestTemplateUrlTemplateCapturingAspect.captureUrlTemplate(RestTemplateUrlTemplateCapturingAspect.java:33)
	at sun.reflect.GeneratedMethodAccessor132.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:620)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:609)
	at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:68)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:655)
	at org.springframework.web.client.RestTemplate$$EnhancerBySpringCGLIB$$d910d584.exchange(<generated>)
	at com.somecompany.someclient.remote.service.impl.QxyzRestCommsServiceImpl.doAuthenticatedPost(QxyzRestCommsServiceImpl.java:96)
	at com.somecompany.someclient.remote.service.impl.BasicThingServiceImpl.create(BasicThingServiceImpl.java:76)
	at com.somecompany.someclient.remote.service.impl.CachingThingServiceImpl.create(CachingThingServiceImpl.java:36)
	at com.somecompany.someclient.remote.service.impl.CachingThingServiceImpl$$FastClassBySpringCGLIB$$35d03493.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:720)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.cache.interceptor.CacheInterceptor$1.invoke(CacheInterceptor.java:52)
	at org.springframework.cache.interceptor.CacheAspectSupport.invokeOperation(CacheAspectSupport.java:320)
	at org.springframework.cache.interceptor.CacheAspectSupport.execute(CacheAspectSupport.java:353)
	at org.springframework.cache.interceptor.CacheAspectSupport.execute(CacheAspectSupport.java:302)
	at org.springframework.cache.interceptor.CacheInterceptor.invoke(CacheInterceptor.java:61)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:655)
	at com.somecompany.someclient.remote.service.impl.CachingThingServiceImpl$$EnhancerBySpringCGLIB$$39ef00a6.create(<generated>)
	at com.somecompany.someclient.remote.service.impl.AaToBbThingService.create(AaToBbThingService.java:45)
	at com.somecompany.someclient.remote.service.impl.CircuitBreakingThingServiceImpl.create(CircuitBreakingThingServiceImpl.java:66)
	at sun.reflect.GeneratedMethodAccessor166.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.netflix.hystrix.contrib.javanica.command.MethodExecutionAction.execute(MethodExecutionAction.java:116)
	at com.netflix.hystrix.contrib.javanica.command.MethodExecutionAction.executeWithArgs(MethodExecutionAction.java:93)
	at com.netflix.hystrix.contrib.javanica.command.MethodExecutionAction.execute(MethodExecutionAction.java:78)
	at com.netflix.hystrix.contrib.javanica.command.GenericCommand$1.execute(GenericCommand.java:47)
	at com.netflix.hystrix.contrib.javanica.command.AbstractHystrixCommand.process(AbstractHystrixCommand.java:146)
	at com.netflix.hystrix.contrib.javanica.command.GenericCommand.run(GenericCommand.java:44)
	at com.netflix.hystrix.HystrixCommand$1.call(HystrixCommand.java:293)
	at com.netflix.hystrix.HystrixCommand$1.call(HystrixCommand.java:289)
	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:46)
	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:35)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:50)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:50)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.Observable.unsafeSubscribe(Observable.java:8460)
	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:51)
	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:35)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:50)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:50)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.Observable.unsafeSubscribe(Observable.java:8460)
	at rx.internal.operators.OperatorSubscribeOn$1.call(OperatorSubscribeOn.java:94)
	at com.netflix.hystrix.strategy.concurrency.HystrixContexSchedulerAction$1.call(HystrixContexSchedulerAction.java:56)
	at com.netflix.hystrix.strategy.concurrency.HystrixContexSchedulerAction$1.call(HystrixContexSchedulerAction.java:47)
	at com.netflix.hystrix.strategy.concurrency.HystrixContexSchedulerAction.call(HystrixContexSchedulerAction.java:69)
	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

   Locked ownable synchronizers:
	- locked <5c11f33b> (a java.util.concurrent.ThreadPoolExecutor$Worker)
```

If I'm reading this right, it looks like we hit a deadlock or infinite waiting state while negotiating the SSL connection to the remote service...and then for some reason the raised exception does not free the hystrix thread?

**Comment by mattrjacobs** [comment]
When using a thread-isolated command, Hystrix defaults to interrupting the thread upon timeout.  As with all code that runs on the JVM, this is best-effort and Hystrix can't make any guarantees about how the code respects/does not respect the interrupt.

**Comment by demaniak** [comment]
Noted, thanks @mattrjacobs . 

So potentially ill-behaving servers/connections that get stuck in a dead read-loop, must always be handled specially (by setting a reasonable SO_TIMEOUT at the connection handler.)

This is the honestly the only issue I have picked up with Hystrix so far (and to be fair, not really a Hystrix issue, as explained above).

Can't speak for @carlmoser , but I can live with this issue being closed.

**Comment by mattrjacobs** [comment]
Yeah, there's really nothing that Hystrix can do - just isolate this misbehaving I/O in a non-application thread (which was one of the prime reasons for creating Hystrix).  Closing.

**Comment by yanglifan** [comment]
@carlmoser Try to invoke `HttpUriRequest.abort()` in `getFallback()` to close the connection

**Comment by vimalk78** [comment]
@mattrjacobs 

> For thread interruption, Hystrix can't guarantee that the interruption actually happens. Like all other code that runs on the JVM, you can only throw an InterruptedException,
after timeout, can we not interrupt the hystrix thread which is blocking on socket waiting for the response ? this way not only user thread, but also hystrix thread is freed to take up other requests

**Comment by demaniak** [comment]
@vimalk78 the problem (in my case), was that there never was a timeout.  The IO-bound thread was hung by the low-level socket read loop that never completed.
And the main thing was - NOT always. The problem creeped in gradually over time, or faster under load.

Once I explicitly got a SO_TIMEOUT set, the socket read timed-out, and Hystrix performed correctly.

In my case, I was using Spring RestTemplate, and had to configure a custom `HttpComponentsClientHttpRequestFactory`, with appropriate configuration to get the SO_TIMEOUT in there.

**Comment by Anubhav007** [comment]
> For thread interruption, Hystrix can't guarantee that the interruption actually happens. Like all other code that runs on the JVM, you can only throw an `InterruptedException`, you can't force the wrapped code to catch it. This is one of the reasons that Hystrix exists - we would much rather that a Hystrix thread gets stuck in this state than an application thread.
> 
> For the metrics issue, it's hard to debug your issue with this info. If you add some breakpoints/printlns, you should be able to loop over the HystrixThreadPoolMetrics.getInstances values and see what instances of metrics are in your code. You should also be able to take a thread dump and see what threads are actually getting setup. Those may help you understand more about what's happening.

Does it mean if there is an exception in some different thread like Rabbit Listener, then it might lead to HystrixRuntime Exception during command.queue().
