### ISSUE TITLE
NoClassDefFoundError:  noclassdeffounderror:org/HdrHistogram/AbstractHistogram

### ISSUE THREAD

**Issue by sandyjoins02** [Netflix/Hystrix#1288]
SEVERE: Servlet.service() for servlet [dispatcher] in context with path [] threw exception [Handler processing failed; nested exception is java.lang.NoClassDefFoundError: 
noclassdeffounderror:org/HdrHistogram/AbstractHistogram] with root cause
java.lang.ClassNotFoundException: org.HdrHistogram.AbstractHistogram
	at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1720)
	at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1571)
	at com.netflix.hystrix.metric.consumer.RollingDistributionStream.<clinit>(RollingDistributionStream.java:52)
	at com.netflix.hystrix.HystrixCommandMetrics.<init>(HystrixCommandMetrics.java:203)
	at com.netflix.hystrix.HystrixCommandMetrics.getInstance(HystrixCommandMetrics.java:134)
	at com.netflix.hystrix.AbstractCommand.initMetrics(AbstractCommand.java:239)
	at com.netflix.hystrix.AbstractCommand.<init>(AbstractCommand.java:165)
	at com.netflix.hystrix.HystrixCommand.<init>(HystrixCommand.java:142)
	at com.netflix.hystrix.HystrixCommand.<init>(HystrixCommand.java:128)

**Comment by mattrjacobs** [comment]
The immediate problem looks like you're not including the HdrHistogram jar.  If you pull in a recent version of Hystrix via a normal dependency mechanism like Maven/Gradle, you should be also pulling in this jar.  

If you need help getting that resolved, please list the version of Hystrix you're using, and what your build process looks like

**Comment by sandyjoins02** [comment]
Hi Matt,
The above issue was resolved.

But now I cant find dependency class:
*com.netflix.config.DynamicIntProperty*
Please help!! I'm stuck.

**Comment by mukteshkrmishra** [comment]
Hi, 

Make sure you have archius core present in your classpath

**Comment by sandyjoins02** [comment]
It definitely is present. Infact I have tried with different archaius jars.

Using:
hystrix-core-1.5.3.jar, archaius2-core-2.0.6.jar,
hystrix-metrics-event-stream-1.5.3.jar, rxjava-1.1.7.jar

**Comment by mukteshkrmishra** [comment]
Are you using any build tool like maven or gradle or adding jars explicitly?

**Comment by sandyjoins02** [comment]
I am adding them explicitly.

**Comment by sandyjoins02** [comment]
Using ANT for build

**Comment by sandyjoins02** [comment]
It suddenly started working with archaius-core-0.7.4.jar

Thanks,

**Comment by mukteshkrmishra** [comment]
Great. I would recommend to always use some build tool, as it will be taking care of this automatically.

**Comment by mattrjacobs** [comment]
Thanks for the answers, @mukteshkrmishra - I appreciate the help!  

@mukteshkrmishra is correct - Hystrix has a few dependencies, and they all need to be present for Hystrix to work.  This is a fairly common state of affairs and is generally best solved by using a tool which manages dependencies for you.
