### ISSUE TITLE
Unable to extract the instance name from config.properties in turbine installation

### ISSUE THREAD

**Issue by shukla-praveen** [Netflix/Hystrix#1327]
steps that I am following to install turbine:
1. Install java8
2. Install jetty
3. Placing turbine.war file inside 

> /usr/share/jetty/webapps/turbine.war

4. config.properties contains

```
turbine.ConfigPropertyBasedDiscovery.default.instances=192.167.33.17
turbine.instanceUrlSuffix=:8080/hystrix-examples-webapp/hystrix.stream
```
5. To start turbine 

`vagrant@s-turbine-hystrix:/usr/share/jetty$ java -Darchaius.configurationSource.additionalUrls=file:///home/vagrant/config.properties -jar start.jar
`

I am getting following java.lang.IllegalArgumentException, also tried all combination in config.properties file like double quote, appending IP address with http://, putting full url in one line.  

Full stacktrace: 
```
Just added and starting handler tuple: <cluster1>_agg_aggClusterEventHandler
2016-08-21 09:11:32 INFO  com.netflix.turbine.handler.HandlerQueueTuple$PerHandlerDispatcher:229 [HandlerQueueTuple$PerHandlerDispatcher] [init]: Per handler dispacher started for: <cluster1>_agg_aggClusterEventHandler
[main] INFO org.mortbay.log - NO JSP Support for , did not find org.apache.jasper.servlet.JspServlet
2016-08-21 09:11:32 INFO  com.netflix.turbine.monitor.instance.InstanceMonitor:186 [InstanceMonitor] [<init>]: Url for host: http://<instance1b>:8080/hystrix-examples-webapp/hystrix.stream <cluster1>
2016-08-21 09:11:32 INFO  com.netflix.turbine.monitor.instance.InstanceMonitor:186 [InstanceMonitor] [<init>]: Url for host: http://<instance2a>:8080/hystrix-examples-webapp/hystrix.stream <cluster2>
2016-08-21 09:11:32 INFO  com.netflix.turbine.handler.TurbineDataDispatcher:176 [TurbineDataDispatcher] [getHandlerQueueTuple]:

Just added and starting handler tuple: <cluster2>_agg_aggClusterEventHandler
2016-08-21 09:11:32 INFO  com.netflix.turbine.handler.HandlerQueueTuple$PerHandlerDispatcher:229 [HandlerQueueTuple$PerHandlerDispatcher] [init]: Per handler dispacher started for: <cluster2>_agg_aggClusterEventHandler
2016-08-21 09:11:32 WARN  com.netflix.turbine.monitor.instance.InstanceMonitor$2:241 [InstanceMonitor$2] [call]: Stopping InstanceMonitor for: <instance1b> <cluster1>
java.lang.IllegalArgumentException: Illegal character in authority at index 7:
http://<instance1b>:8080/hystrix-examples-webapp/hystrix.stream
       	at java.net.URI.create(URI.java:852)
       	at org.apache.http.client.methods.HttpGet.<init>(HttpGet.java:69)
       	at com.netflix.turbine.monitor.instance.InstanceMonitor.init(InstanceMonitor.java:305)
       	at com.netflix.turbine.monitor.instance.InstanceMonitor.access$100(InstanceMonitor.java:103)
       	at com.netflix.turbine.monitor.instance.InstanceMonitor$2.call(InstanceMonitor.java:235)
       	at com.netflix.turbine.monitor.instance.InstanceMonitor$2.call(InstanceMonitor.java:229)
       	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
       	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
       	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
       	at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.URISyntaxException: Illegal character in authority at index 7: http://<instance1b>:8080/hystrix-examples-webapp/hystrix.stream
       	at java.net.URI$Parser.fail(URI.java:2848)
       	at java.net.URI$Parser.parseAuthority(URI.java:3186)
       	at java.net.URI$Parser.parseHierarchical(URI.java:3097)
       	at java.net.URI$Parser.parse(URI.java:3053)
       	at java.net.URI.<init>(URI.java:588)
       	at java.net.URI.create(URI.java:850)
       	... 9 more
2016-08-21 09:11:32 INFO  com.netflix.turbine.monitor.instance.InstanceMonitor:331 [InstanceMonitor] [cleanup]: Single Server event publisher releasing http client connection for: <instance1b> <cluster1>
2016-08-21 09:11:32 INFO  com.netflix.turbine.monitor.cluster.AggregateClusterMonitor$AggStatsEventHandler:285 [AggregateClusterMonitor$AggStatsEventHandler] [handleHostLost]: Host lost: <instance1b>, adding to time based cache
```

**Comment by shukla-praveen** [comment]
Issue resolved using below config.properites file
```
turbine.aggregator.clusterConfig=PROD
turbine.instanceUrlSuffix.PROD=/hystrix.stream
turbine.ConfigPropertyBasedDiscovery.PROD.instances=192.168.33.17:8989/hystrix-examples-webapp
```

But I think configuration defined for config.properties in the README [https://github.com/Netflix/Hystrix/wiki/Dashboard](https://github.com/Netflix/Hystrix/wiki/Dashboard)
was not woking properly. should we change the documentation ? 
sorry for trouble :)

**Comment by mattrjacobs** [comment]
No problem, thanks for letting us know you got this resolved.
