### ISSUE TITLE
Thread may be hung, creating javacore files in Websphere.

### ISSUE THREAD

**Issue by ManiKandanCBE** [Netflix/Hystrix#1400]
I'm connecting to the hystrix stream servlet from the dashboard. The stream servlet is deployed to Websphere application server. If I keep the dashboard open for a long time, websphere says that the thread might be hung & it created a javacore file in 10mins. Below is the entry that is being captured in javacore file.

3XMTHREADINFO      "WebContainer : 7" J9VMThread:0x0000000054C61800, j9thread_t:0x00007F3E1C17A640, java/lang/Thread:0x00000000077CDB80, state:CW, prio=5
3XMJAVALTHREAD            (java/lang/Thread getId:0xC8, isDaemon:true)
3XMTHREADINFO1            (native thread ID:0x535F, native priority:0x5, native policy:UNKNOWN, vmstate:CW, vm thread flags:0x00000401)
3XMTHREADINFO2            (native stack address range from:0x00007F3DEC6D5000, to:0x00007F3DEC716000, size:0x41000)
3XMCPUTIME               CPU usage total: 1.639321976 secs
3XMHEAPALLOC             Heap bytes allocated since last GC cycle=0 (0x0)
3XMTHREADINFO3           Java callstack:
4XESTACKTRACE                at java/lang/Thread.sleep(Native Method)
4XESTACKTRACE                at java/lang/Thread.sleep(Thread.java:925(Compiled Code))
4XESTACKTRACE                at com/netflix/hystrix/contrib/sample/stream/HystrixSampleSseServlet.handleRequest(HystrixSampleSseServlet.java:165(Compiled Code))
4XESTACKTRACE                at com/netflix/hystrix/contrib/sample/stream/HystrixSampleSseServlet.doGet(HystrixSampleSseServlet.java:74)

In #821 it was specified that it is just a warning from websphere. But my issue is, after the first javacore file is being created, for every 3 minute websphere keeps on creating javacore files until the dashboard gets closed. This is consuming more memory leading to outofmemory issue. Is there a way we can over come this issue?

**Comment by mattrjacobs** [comment]
The existing implementation of the metrics stream uses SSE, which is a long-running thread.  In a different issue (https://github.com/Netflix/Hystrix/issues/1117#issuecomment-255451900), @gangchen03 contributed an alternative architecture for streaming metrics without using a long-running thread.  IT may be worth exploring if that works better for your use-case.

**Comment by spencergibb** [comment]
Spring Cloud also supports streaming metrics via rabbitmq or kafka (more possible in the future).

**Comment by ManiKandanCBE** [comment]
The above solutions might consume some amount of my time. As I'm looking for some immediate remedy, I modified the hystrix stream servlet to stop processing after certain amount of time. When the servlet completed the process, the thread gets free, also the EventSource used in hystrix dashboard by default resets the connection when the servlet connection gets completed. So this seems fine for me to overcome the issue with Servlet.

But there is another similar issue I'm facing. Since we have a clustered environment, we are using Turbine-Web to combine the streams from the cluster. Turbine by default is reconnecting if the servlet connection is closed. As we have deployed Turbine to Websphere, this is making the turbine thread to be alive for a long time & causing the java core dumps to get created & blocking the memory.

Is there a way I can stop the turbine from connecting/reconnecting automatically to the configured cluster?

**Comment by mukteshkrmishra** [comment]
I believe there is no straight forward way to stop turbine from doing this. But you can update properties like : turbine.ConfigPropertyBasedDiscovery.default.instances or turbine.instanceUrlSuffix so that turbine does not do any processing. I have not tried this but you can give it a shot.

**Comment by ManiKandanCBE** [comment]
Is there any alternate open source API that could do the job of turbine?

**Comment by mukteshkrmishra** [comment]
Well once you tap the metrics you can push them into anywhere for eg: push them into Rabbit MQ or Kafka and on top of it create a dashboard using Kibana. Alternatively you can use statsd or collectd or riemann.

**Comment by mukteshkrmishra** [comment]
@spencergibb : In our use case we do not use turbine or hystrix dashboard. We tap the metrics and then pushg them into a facade which exposes to various client implementations like SQS. Riemann, Kafka, Spring XD and Rabbit MQ. Ours is a event driven model. We publish the data to a a facade and subscribers can choose any of the above implementations to consume it and use it for creating dashboards using technologeis like d3 or Kibana.

**Comment by mattrjacobs** [comment]
Closing due to inactivity.  Please re-open if there's more to discuss
