### ISSUE TITLE
HystrixNetworkAuditorEventListener#handleNetworkEvent() is not invoked when encountered with Simple Network Excpetions

### ISSUE THREAD

**Issue by karthikitzmi** [Netflix/Hystrix#1425]
handleNetworkEvent() is  not invoked with few Simple Network exceptions. Here is the link for one of them.

http://stackoverflow.com/questions/40643621/hystrixnetworkauditoreventlistener-is-not-invoked-upon-failure-in-connecting-to

Is there anything that could be done. Not sure if it's the new issue . Any info on this issue would be helpful.

**Comment by mattrjacobs** [comment]
Just to make sure we're on the same page, the intent of the network auditor is not to detect anything about successful/network connections.  The intent is just to find all network connections that are made outside of a Hystrix command.  These are network operations which don't get the bulkheading that Hystrix offers, and are latent risks to the system.

The agent looks for Java stack traces which include `java.net.Socket$2` or `java.nio.channels.SocketChannel`, so it's fairly naive.

If you can include the actual stack trace of the network connection you're making, then we can determine if one of these regexes should be matching or not.

**Comment by karthikitzmi** [comment]
Thanks for the prompt reply. 

To be clear,  I just wrote a simple program that connects to local URL. It doesn't have hystrix command in code. So I expected the HystrixNetworkAuditorAgent to detect it as its not wrapped in Hystrix command.

Here is the stacktrace from my main() method. Its not detected by HystrixNetworkAuditorAgent.

java.net.ConnectException: Connection refused: connect
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.PlainSocketImpl.doConnect(PlainSocketImpl.java:351)
	at java.net.PlainSocketImpl.connectToAddress(PlainSocketImpl.java:213)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:200)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:366)
	at java.net.Socket.connect(Socket.java:529)
	at java.net.Socket.connect(Socket.java:478)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:163)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:411)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:525)
	at sun.net.www.http.HttpClient.<init>(HttpClient.java:208)
	at sun.net.www.http.HttpClient.New(HttpClient.java:291)
	at sun.net.www.http.HttpClient.New(HttpClient.java:310)
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:987)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:923)
	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:841)

**Comment by mattrjacobs** [comment]
From what I can tell, that stack trace isn't matched by the hard-coded regex that `HystrixNetworkAuditorAgent` uses.  I'm not sure if that's an artifact of making a local connection or not.  I think the next steps are:

1) Try running the agent against real calls to remote services and seeing if it is working the way you expect.
2) If you have examples of undetected network calls, then a PR for an addition to the regexes would be great.

**Comment by mattrjacobs** [comment]
Closing due to inactivity
