### ISSUE TITLE
Question regarding how a state is reached

### ISSUE THREAD

**Issue by DangerPete** [Netflix/Hystrix#1440]
Hi, I've been using Hystrix in the observalbe fashion (hystrix core version 1.5.5) and from time to time an exception is thrown such as `execution attempted while in state : UNSUBSCRIBED`
Capturing the execution events I can see different values: sometimes it's `[FAILURE FALLBACK_MISSING]` other times it's `[CANCELLED]`.

My question is simply- why can it get into this state and is it something I'm doing wrong?

Cheers

Peter

**Comment by mattrjacobs** [comment]
Those are states of a state machine that are used for Hystrix internals to keep track of what's happened so far, and what is allowed to happen.  That error is not yours, it's likely an edge case that's not handled properly.  

Can you send me the way that the Observable produced by Hystrix is used?  That might give me a clue on how to write a unit test that will repro the issue.  Thanks!

**Comment by DangerPete** [comment]
Hi Matt,

As it's private code I've done my best to extract what I think will be the relevant parts. I hope it still makes sense, as even before extraction it's not the most straight forward :)

```
public FinalResult theBigOne() {

  //Shortened for brevity sake
  Observable oneObservable = createFirstObservable(firstTask);
  Observable failingObservable = buildSecondCall();
  //Shortened for brevity sake
  Observable twoObservable = createAnotherObservable(secondTask);

  return oneObservable
            .flatMap(oneResult -> 
              Observable
                .zip(failingObservable, twoObservable,
                        (result1, result2) -> moreStuffToDo(result1, result2))
                .flatMap(transformedResult -> transformedResult));
                .toBlocking()
                .single();
}

public Observable buildSecondCall() {
  return observeGeneric(workingTask)
    .single()
    .flatMap(
      (r) ->  r.isFailure()
                              ? callFallback()
                              : Observable.just(r))
    .onErrorResumeNext(e -> callFallback())
    .flatMap(transformResponse()));
}

public Observable observeGeneric(Supplier task) {
  TaskCommand command = new TaskCommand(task);
  return command.toObservable().onErrorResumeNext(e -> Observable.error(handleCommandException(e)))
}

public Observable createFailingObservable() {
  observeGeneric(FAILING_TASK).single().onErrorReturn(WrappedResponse::new);
}
```

Let me try and talk it through too. We have three tasks we want done concurrently.
After the first is completed successfully (`oneObservable`) then we wait until the second 'failingObservable' and third `twoObservable complete`. The output of these two calls are then used to do more work (which entails observables, more zipping!), the result of which is finally returned.

The part which is reporting errors is one of the observables in the first zip, so I went into further details on how we create that as it's also slightly more complex than the other two:
This involves attempting an observable task, if it throws an error or the output is deemed as a failure we attempt a second task, otherwise the result is transformed and returned. If this second task fails the error is thrown, otherwise the result is transformed and returned.
It is this second task which is throwing the IllegalStateException.

I don't know if it will help, but I've got a copy of the stacktrace:
```
java.lang.IllegalStateException: execution attempted while in state : UNSUBSCRIBED
    at com.netflix.hystrix.AbstractCommand$17.call
    at com.netflix.hystrix.AbstractCommand$17.call
    at rx.internal.operators.OnSubscribeDefer.call
    at rx.internal.operators.OnSubscribeDefer.call
    at rx.internal.operators.OnSubscribeLift.call
    at rx.internal.operators.OnSubscribeLift.call
    at rx.internal.operators.OnSubscribeLift.call
    at rx.internal.operators.OnSubscribeLift.call
    at rx.Observable.unsafeSubscribe
    at rx.internal.operators.OperatorSubscribeOn$1.call
    at com.netflix.hystrix.strategy.concurrency.HystrixContexSchedulerAction$1.call
    at com.netflix.hystrix.strategy.concurrency.HystrixContexSchedulerAction$1.call
    at com.sciencedirect.sdtech.hystrix.concurrency.HystrixMDCLoggingCallable.call
    at com.netflix.hystrix.strategy.concurrency.HystrixContexSchedulerAction.call
    at rx.internal.schedulers.ScheduledAction.run
    at java.util.concurrent.Executors$RunnableAdapter.call
    at java.util.concurrent.FutureTask.run
    at java.util.concurrent.ThreadPoolExecutor.runWorker
    at java.util.concurrent.ThreadPoolExecutor$Worker.run
    at java.lang.Thread.run
```

Hope this was helpful in any way!

**Comment by rotilho** [comment]
I have the same issue whenever I have a high load and the return type is `Void`

```
java.lang.IllegalStateException: execution attempted while in state : UNSUBSCRIBED
	at com.netflix.hystrix.AbstractCommand$17.call(AbstractCommand.java:656) ~[hystrix-core-1.5.12.jar:1.5.12]
	at com.netflix.hystrix.AbstractCommand$17.call(AbstractCommand.java:651) ~[hystrix-core-1.5.12.jar:1.5.12]
	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:46) ~[rxjava-1.1.10.jar:1.1.10]
	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:35) ~[rxjava-1.1.10.jar:1.1.10]
	at rx.Observable.unsafeSubscribe(Observable.java:10211) ~[rxjava-1.1.10.jar:1.1.10]
	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41) [rxjava-1.1.10.jar:1.1.10]
	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30) [rxjava-1.1.10.jar:1.1.10]
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48) [rxjava-1.1.10.jar:1.1.10]
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30) [rxjava-1.1.10.jar:1.1.10]
	at rx.Observable.unsafeSubscribe(Observable.java:10211) ~[rxjava-1.1.10.jar:1.1.10]
	at rx.internal.operators.OperatorSubscribeOn$1.call(OperatorSubscribeOn.java:94) [rxjava-1.1.10.jar:1.1.10]
	at com.netflix.hystrix.strategy.concurrency.HystrixContexSchedulerAction$1.call(HystrixContexSchedulerAction.java:56) [hystrix-core-1.5.12.jar:1.5.12]
	at com.netflix.hystrix.strategy.concurrency.HystrixContexSchedulerAction$1.call(HystrixContexSchedulerAction.java:47) [hystrix-core-1.5.12.jar:1.5.12]
	at org.springframework.cloud.sleuth.instrument.hystrix.SleuthHystrixConcurrencyStrategy$HystrixTraceCallable.call(SleuthHystrixConcurrencyStrategy.java:154) [spring-cloud-sleuth-core-1.2.1.RELEASE.jar:1.2.1.RELEASE]
	at com.netflix.hystrix.strategy.concurrency.HystrixContexSchedulerAction.call(HystrixContexSchedulerAction.java:69) [hystrix-core-1.5.12.jar:1.5.12]
	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55) [rxjava-1.1.10.jar:1.1.10]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_121]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_121]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_121]
```

**Comment by IshaMarwah** [comment]
Hi there,

Is there any update on the above issue reported by @DangerPete ?

Thanks
