### ISSUE TITLE
can hystrixCommand run()  ProceedingJoinPoint.proceed?---can hystrixCommand use localThread?

### ISSUE THREAD

**Issue by budye509** [Netflix/Hystrix#1494]
```
HystrixAspect:
@Around(value = "point()")
	public Object aroundAdvice(final ProceedingJoinPoint joinPoint) throws Throwable {
		BaseHystrixCommand<Object> command = new BaseHystrixCommand<Object>(commandKey, commandGroupKey, threadPoolKey, 5000) {
			@Override
			protected Object run() throws Exception {
				Object data = null;
				try {
					data = joinPoint.proceed();
				} catch (Throwable e) {
					e.printStackTrace();
				}
				return data;
			}
		};
		return command.execute();
	}
```

Exception:
```
java.lang.IllegalStateException: No MethodInvocation found: Check that an AOP invocation is in progress, and that the ExposeInvocationInterceptor is upfront in the interceptor chain. Specifically, note that advices with order HIGHEST_PRECEDENCE will execute before ExposeInvocationInterceptor!
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.currentInvocation(ExposeInvocationInterceptor.java:73)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.getJoinPointMatch(AbstractAspectJAdvice.java:644)
	at org.springframework.aop.aspectj.AspectJMethodBeforeAdvice.before(AspectJMethodBeforeAdvice.java:40)
	at org.springframework.aop.framework.adapter.MethodBeforeAdviceInterceptor.invoke(MethodBeforeAdviceInterceptor.java:51)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:168)
	at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:85)
	at com.support.aspect.HystrixAspect$1.run(HystrixAspect.java:53)
	at com.netflix.hystrix.HystrixCommand$2.call(HystrixCommand.java:299)
	at com.netflix.hystrix.HystrixCommand$2.call(HystrixCommand.java:295)
	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:46)
	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:35)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.Observable.unsafeSubscribe(Observable.java:9861)
	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:51)
	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:35)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.Observable.unsafeSubscribe(Observable.java:9861)
	at rx.internal.operators.OperatorSubscribeOn$1.call(OperatorSubscribeOn.java:94)
	at com.netflix.hystrix.strategy.concurrency.HystrixContexSchedulerAction$1.call(HystrixContexSchedulerAction.java:56)
	at com.netflix.hystrix.strategy.concurrency.HystrixContexSchedulerAction$1.call(HystrixContexSchedulerAction.java:47)
	at com.netflix.hystrix.strategy.concurrency.HystrixContexSchedulerAction.call(HystrixContexSchedulerAction.java:69)
	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by mattrjacobs** [comment]
@budye509 I'm unfamiliar with AOP.  Can you explain why that error is being thrown?

**Comment by budye509** [comment]
@mattrjacobs  AOP  is runing a thread,  the Aop  method  'ProceedingJoinPoint.proceed' is in 'hystrixCommand run()', but 'hystrixCommand run()' use other thread pool.
so AOP thread is not continuous.  Do you know What are the best solution?

**Comment by mattrjacobs** [comment]
Hystrix will use its own thread if configured to use thread isolation.  You may choose to use semaphore isolation if you wish to: https://github.com/Netflix/Hystrix/wiki/Configuration#execution.isolation.strategy

**Comment by budye509** [comment]
@mattrjacobs  Problem has been solved.  thank you very much.
