### ISSUE TITLE
java.lang.NoClassDefFoundError: Could not initialize class com.netflix.hystrix.strategy.HystrixPlugins$LazyHolder

### ISSUE THREAD

**Issue by cyxroot** [Netflix/Hystrix#1500]
Caused by: java.lang.NoClassDefFoundError: Could not initialize class com.netflix.hystrix.strategy.HystrixPlugins$LazyHolder
        at com.netflix.hystrix.strategy.HystrixPlugins.getInstance(HystrixPlugins.java:103)
        at com.netflix.hystrix.strategy.properties.HystrixPropertiesFactory.getCommandProperties(HystrixPropertiesFactory.java:62)
        at com.netflix.hystrix.AbstractCommand.initCommandProperties(AbstractCommand.java:204)
        at com.netflix.hystrix.AbstractCommand.<init>(AbstractCommand.java:163)
        at com.netflix.hystrix.HystrixCommand.<init>(HystrixCommand.java:147)
        at com.netflix.hystrix.HystrixCommand.<init>(HystrixCommand.java:133)
        at com.candao.product.api.hystrix.DubboHystrixCommand.<init>(DubboHystrixCommand.java:36)
        at com.candao.product.api.hystrix.DubboHystrixFilter.invoke(DubboHystrixFilter.java:22)
        at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91)
        at com.alibaba.dubbo.rpc.protocol.dubbo.filter.FutureFilter.invoke(FutureFilter.java:53)
        at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91)
        at com.alibaba.dubbo.monitor.support.MonitorFilter.invoke(MonitorFilter.java:65)
        at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91)
        at com.alibaba.dubbo.rpc.filter.ConsumerContextFilter.invoke(ConsumerContextFilter.java:48)
        at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91)
        at com.alibaba.dubbo.rpc.listener.ListenerInvokerWrapper.invoke(ListenerInvokerWrapper.java:74)
        at com.alibaba.dubbo.rpc.protocol.InvokerWrapper.invoke(InvokerWrapper.java:53)
        at com.alibaba.dubbo.rpc.cluster.support.FailoverClusterInvoker.doInvoke(FailoverClusterInvoker.java:77)

**Comment by mattrjacobs** [comment]
I can't really tell from this stack trace in isolation what's happening.  

Can you provide more details on what sort of initialization you're doing around Hystrix in your application and what other stack traces are present at initialization time?

**Comment by mattrjacobs** [comment]
Closing due to inactivity
