### ISSUE TITLE
Set maximumSize using @HystrixCommand annotation

### ISSUE THREAD

**Issue by ilyas-keser** [Netflix/Hystrix#1565]
It is not possible to set the maximumSize using the HystrixCommand annotation. Example:
```
  @HystrixCommand(ignoreExceptions = MyException.class,
    threadPoolProperties = {
      @HystrixProperty(name = "coreSize", value = "20"),
      @HystrixProperty(name = "maximumSize", value = "25"),
      @HystrixProperty(name = "allowMaximumSizeToDivergeFromCoreSize", value = "true")
  })
  public MyPerson getMyPerson(...)
```

Hystrix version: **1.5.11**

Exception:

```
Caused by: java.lang.IllegalArgumentException: unknown thread pool property: maximumSize
	at com.netflix.hystrix.contrib.javanica.conf.HystrixPropertiesManager.initializeProperties(HystrixPropertiesManager.java:125)
	at com.netflix.hystrix.contrib.javanica.conf.HystrixPropertiesManager.initializeThreadPoolProperties(HystrixPropertiesManager.java:108)
	at com.netflix.hystrix.contrib.javanica.command.GenericSetterBuilder.build(GenericSetterBuilder.java:81)
```

**Comment by mattrjacobs** [comment]
@dmgcodevil Any cycles to work on this?

@ilyas-keser Any interest in submitting a PR for this functionality?

**Comment by dmgcodevil** [comment]
PR: https://github.com/Netflix/Hystrix/pull/1572

**Comment by ilyas-keser** [comment]
@dmgcodevil Is it possible to set allowMaximumSizeToDivergeFromCoreSize? The maximumSize setting only takes effect if you also set the allowMaximumSizeToDivergeFromCoreSize setting.

**Comment by mattrjacobs** [comment]
@ilyas-keser I just submitted #1584

**Comment by ilyas-keser** [comment]
@mattrjacobs Thanks!

**Comment by dmgcodevil** [comment]
we can close
