### ISSUE TITLE
Static method issue

### ISSUE THREAD

**Issue by priyadarsh** [Netflix/Hystrix#1631]
Hi
The below NPE is thrown when Hystrix annotation is applied on static methods.

java.lang.NullPointerException: null
	at com.netflix.hystrix.contrib.javanica.utils.AopUtils.getMethodFromTarget(AopUtils.java:50)
	at com.netflix.hystrix.contrib.javanica.aop.aspectj.HystrixCommandAspect.methodsAnnotatedWithHystrixCommand(HystrixCommandAspect.java:88)

**Comment by priyadarsh** [comment]
Just to be specific, I am using the com.netflix.hystrix.contrib.javanica.annotation.HystrixCommand  in Javanica project

**Comment by priyadarsh** [comment]
Submitted pull request for the same
https://github.com/Netflix/Hystrix/pull/1632
