### ISSUE TITLE
HystrixTimeoutException when accessing an API endpoint

### ISSUE THREAD

**Issue by srikumarcs** [Netflix/Hystrix#1660]
Hello,

This is my first time raising an issue here, so I apologise if I am not following any of the posting guidelines here. With that out of the way, I am trying to connect to an external endpoint using Hystrix wrapped around a Feign client. The Feign client uses OkHTTP as its HTTP Client. What I am observing is that when I try to access this endpoint (which is hosted in the same network as the Hystrix client) I get HystrixTimeoutException. I am not able to figure out what this is the case. Reading up on the documentation, I gather that this is an exception thats thrown by Hystrix when the Hystrix Command timeouts earlier than the end point returning back with the response. I have tried to increase the timeout using the appropriate setting and it still doesn't seem to make a difference. I can see that the circuit is closed as well (In case any one wonders whats happening on that front). 

This is my Hystrix set up - 
isolation mode - thread
timeoutInMilliSeconds - 60000 (I have tried 30000 & higher values as well)

In case any one wonders, the set up of Hystrix looks ok to me. This is because I am able to connect to an external API (outside of our network) without any problems. I can see that it behaves as expected (comes back with success when it should and goes to the fallback method when it should). Here is the complete stack trace 

<pre>
com.netflix.hystrix.exception.HystrixTimeoutException: null
	at com.netflix.hystrix.AbstractCommand$HystrixObservableTimeoutOperator$1$1.run(AbstractCommand.java:1154)
	at com.netflix.hystrix.strategy.concurrency.HystrixContextRunnable$1.call(HystrixContextRunnable.java:45)
	at com.netflix.hystrix.strategy.concurrency.HystrixContextRunnable$1.call(HystrixContextRunnable.java:41)
	at org.springframework.security.concurrent.DelegatingSecurityContextCallable.call(DelegatingSecurityContextCallable.java:86)
	at com.netflix.hystrix.strategy.concurrency.HystrixContextRunnable.run(HystrixContextRunnable.java:61)
	at com.netflix.hystrix.AbstractCommand$HystrixObservableTimeoutOperator$1.tick(AbstractCommand.java:1159)
	at com.netflix.hystrix.util.HystrixTimer$1.run(HystrixTimer.java:99)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
</pre>

**Comment by hamzafarooq951** [comment]
Did you get to resolve this issue? any feedback or suggestion

**Comment by ThinkingMan007** [comment]
好的，我已收到。
