### ISSUE TITLE
Spring boot 2.0.1.RELEASE and spring-cloud-starter-netflix-hystrix-dashboard Finchley.M9

### ISSUE THREAD

**Issue by jmaciel33** [Netflix/Hystrix#1793]
I have a problem to use Spring boot 2.0.1.RELEASE and spring-cloud-starter-netflix-hystrix-dashboard Finchley.M9, when use the annotation @EnableHystrixDashboard, I receive an error.

If a i remove @EnableHystrixDashboard the circuit break works well.

2018-04-19 21:19:28.721  INFO 80724 --- [           main] s.c.a.AnnotationConfigApplicationContext : Refreshing org.springframework.context.annotation.AnnotationConfigApplicationContext@76508ed1: startup date [Thu Apr 19 21:19:28 BRT 2018]; root of context hierarchy
2018-04-19 21:19:29.182  INFO 80724 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'configurationPropertiesRebinderAutoConfiguration' of type [org.springframework.cloud.autoconfigure.ConfigurationPropertiesRebinderAutoConfiguration$$EnhancerBySpringCGLIB$$330c69ff] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::        (v2.0.1.RELEASE)

2018-04-19 21:19:29.866  INFO 80724 --- [           main] com.sample.microservices.Application     : The following profiles are active: dev
2018-04-19 21:19:29.895  INFO 80724 --- [           main] ConfigServletWebServerApplicationContext : Refreshing org.springframework.boot.web.servlet.context.AnnotationConfigServletWebServerApplicationContext@7a362b6b: startup date [Thu Apr 19 21:19:29 BRT 2018]; parent: org.springframework.context.annotation.AnnotationConfigApplicationContext@76508ed1
2018-04-19 21:19:31.259  INFO 80724 --- [           main] o.s.b.f.s.DefaultListableBeanFactory     : Overriding bean definition for bean 'environmentWebEndpointExtension' with a different definition: replacing [Root bean: class [null]; scope=; abstract=false; lazyInit=false; autowireMode=3; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=org.springframework.boot.actuate.autoconfigure.env.EnvironmentEndpointAutoConfiguration; factoryMethodName=environmentWebEndpointExtension; initMethodName=null; destroyMethodName=(inferred); defined in class path resource [org/springframework/boot/actuate/autoconfigure/env/EnvironmentEndpointAutoConfiguration.class]] with [Root bean: class [null]; scope=; abstract=false; lazyInit=false; autowireMode=3; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=org.springframework.cloud.autoconfigure.LifecycleMvcEndpointAutoConfiguration$EndpointConfiguration; factoryMethodName=environmentWebEndpointExtension; initMethodName=null; destroyMethodName=(inferred); defined in class path resource [org/springframework/cloud/autoconfigure/LifecycleMvcEndpointAutoConfiguration$EndpointConfiguration.class]]
2018-04-19 21:19:31.640  INFO 80724 --- [           main] o.s.cloud.context.scope.GenericScope     : BeanFactory id=284b9f56-9027-3b25-8e86-7f9689488782
2018-04-19 21:19:32.151  INFO 80724 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'org.springframework.cloud.autoconfigure.ConfigurationPropertiesRebinderAutoConfiguration' of type [org.springframework.cloud.autoconfigure.ConfigurationPropertiesRebinderAutoConfiguration$$EnhancerBySpringCGLIB$$330c69ff] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2018-04-19 21:19:32.917  INFO 80724 --- [           main] org.xnio                                 : XNIO version 3.3.8.Final
2018-04-19 21:19:32.960  INFO 80724 --- [           main] org.xnio.nio                             : XNIO NIO Implementation Version 3.3.8.Final
2018-04-19 21:19:33.170  WARN 80724 --- [           main] io.undertow.websockets.jsr               : UT026009: XNIO worker was not set on WebSocketDeploymentInfo, the default worker will be used
2018-04-19 21:19:33.171  WARN 80724 --- [           main] io.undertow.websockets.jsr               : UT026010: Buffer pool was not set on WebSocketDeploymentInfo, the default pool will be used
2018-04-19 21:19:33.242  INFO 80724 --- [           main] io.undertow.servlet                      : Initializing Spring embedded WebApplicationContext
2018-04-19 21:19:33.242  INFO 80724 --- [           main] o.s.web.context.ContextLoader            : Root WebApplicationContext: initialization completed in 3347 ms
2018-04-19 21:19:33.808  INFO 80724 --- [           main] o.s.b.w.servlet.ServletRegistrationBean  : Servlet proxyStreamServlet mapped to [/proxy.stream]
2018-04-19 21:19:33.815  INFO 80724 --- [           main] o.s.b.w.servlet.ServletRegistrationBean  : Servlet dispatcherServlet mapped to [/]
2018-04-19 21:19:33.822  INFO 80724 --- [           main] o.s.b.w.servlet.FilterRegistrationBean   : Mapping filter: 'characterEncodingFilter' to: [/*]
2018-04-19 21:19:33.824  INFO 80724 --- [           main] o.s.b.w.servlet.FilterRegistrationBean   : Mapping filter: 'hiddenHttpMethodFilter' to: [/*]
2018-04-19 21:19:33.824  INFO 80724 --- [           main] o.s.b.w.servlet.FilterRegistrationBean   : Mapping filter: 'httpPutFormContentFilter' to: [/*]
2018-04-19 21:19:33.824  INFO 80724 --- [           main] o.s.b.w.servlet.FilterRegistrationBean   : Mapping filter: 'requestContextFilter' to: [/*]
2018-04-19 21:19:33.824  INFO 80724 --- [           main] o.s.b.w.servlet.FilterRegistrationBean   : Mapping filter: 'httpTraceFilter' to: [/*]
2018-04-19 21:19:33.825  INFO 80724 --- [           main] o.s.b.w.servlet.FilterRegistrationBean   : Mapping filter: 'webMvcMetricsFilter' to: [/*]
2018-04-19 21:19:34.118  WARN 80724 --- [           main] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'freeMarkerConfigurer' defined in org.springframework.cloud.netflix.hystrix.dashboard.HystrixDashboardConfiguration: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.web.servlet.view.freemarker.FreeMarkerConfigurer]: Factory method 'freeMarkerConfigurer' threw exception; nested exception is java.lang.NoClassDefFoundError: freemarker/cache/TemplateLoader
2018-04-19 21:19:34.135  INFO 80724 --- [           main] ConditionEvaluationReportLoggingListener : 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2018-04-19 21:19:34.155 ERROR 80724 --- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'freeMarkerConfigurer' defined in org.springframework.cloud.netflix.hystrix.dashboard.HystrixDashboardConfiguration: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.web.servlet.view.freemarker.FreeMarkerConfigurer]: Factory method 'freeMarkerConfigurer' threw exception; nested exception is java.lang.NoClassDefFoundError: freemarker/cache/TemplateLoader
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:587) ~[spring-beans-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1250) ~[spring-beans-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1099) ~[spring-beans-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:541) ~[spring-beans-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:501) ~[spring-beans-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:317) ~[spring-beans-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:228) ~[spring-beans-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:315) ~[spring-beans-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199) ~[spring-beans-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:760) ~[spring-beans-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:869) ~[spring-context-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:550) ~[spring-context-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:140) ~[spring-boot-2.0.1.RELEASE.jar:2.0.1.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:759) [spring-boot-2.0.1.RELEASE.jar:2.0.1.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:395) [spring-boot-2.0.1.RELEASE.jar:2.0.1.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:327) [spring-boot-2.0.1.RELEASE.jar:2.0.1.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1255) [spring-boot-2.0.1.RELEASE.jar:2.0.1.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1243) [spring-boot-2.0.1.RELEASE.jar:2.0.1.RELEASE]
	at com.sample.microservices.Application.main(Application.java:16) [classes/:na]
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.web.servlet.view.freemarker.FreeMarkerConfigurer]: Factory method 'freeMarkerConfigurer' threw exception; nested exception is java.lang.NoClassDefFoundError: freemarker/cache/TemplateLoader
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185) ~[spring-beans-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:579) ~[spring-beans-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	... 18 common frames omitted
Caused by: java.lang.NoClassDefFoundError: freemarker/cache/TemplateLoader
	at org.springframework.cloud.netflix.hystrix.dashboard.HystrixDashboardConfiguration.freeMarkerConfigurer(HystrixDashboardConfiguration.java:82) ~[spring-cloud-netflix-hystrix-dashboard-2.0.0.M8.jar:2.0.0.M8]
	at org.springframework.cloud.netflix.hystrix.dashboard.HystrixDashboardConfiguration$$EnhancerBySpringCGLIB$$3339d0c3.CGLIB$freeMarkerConfigurer$1(<generated>) ~[spring-cloud-netflix-hystrix-dashboard-2.0.0.M8.jar:2.0.0.M8]
	at org.springframework.cloud.netflix.hystrix.dashboard.HystrixDashboardConfiguration$$EnhancerBySpringCGLIB$$3339d0c3$$FastClassBySpringCGLIB$$7888c81f.invoke(<generated>) ~[spring-cloud-netflix-hystrix-dashboard-2.0.0.M8.jar:2.0.0.M8]
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228) ~[spring-core-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:361) ~[spring-context-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.cloud.netflix.hystrix.dashboard.HystrixDashboardConfiguration$$EnhancerBySpringCGLIB$$3339d0c3.freeMarkerConfigurer(<generated>) ~[spring-cloud-netflix-hystrix-dashboard-2.0.0.M8.jar:2.0.0.M8]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_152]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_152]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_152]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_152]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154) ~[spring-beans-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	... 19 common frames omitted
Caused by: java.lang.ClassNotFoundException: freemarker.cache.TemplateLoader
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[na:1.8.0_152]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[na:1.8.0_152]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:338) ~[na:1.8.0_152]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.8.0_152]
	... 30 common frames omitted

The project and log is attached to the issue.

[ms-sample-rest.zip](https://github.com/Netflix/Hystrix/files/1930167/ms-sample-rest.zip)

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.cloud.client.circuitbreaker.EnableCircuitBreaker;
import org.springframework.cloud.netflix.hystrix.EnableHystrix;
import org.springframework.cloud.netflix.hystrix.dashboard.EnableHystrixDashboard;
```

@SpringBootApplication
@EnableCircuitBreaker
@EnableHystrix
@EnableHystrixDashboard
public class Application {

	public static void main(String[] args) {
		SpringApplication.run(Application.class, args);
	}

}
```

**Comment by spencergibb** [comment]
This is not the spring cloud Netflix issue tracker

**Comment by zhou-jered** [comment]
use stackoverflow instead please

**Comment by jmaciel33** [comment]
thank you

**Comment by TomCools** [comment]
https://github.com/spring-cloud/spring-cloud-netflix <- Issues with Spring Cloud Netflix belong here
