### ISSUE TITLE
@HystrixCommand   Class not found error

### ISSUE THREAD

**Issue by codewithwind** [Netflix/Hystrix#1800]
when i use @HystrixCommand in my project, a problem occur

code:
    @HystrixCommand(groupKey= "defaultQueryProcess",
            commandKey = "queryProcess",
            fallbackMethod = "fallback",
            threadPoolProperties = {
                    @HystrixProperty(name = "coreSize", value = "20"),
                    @HystrixProperty(name = "maxQueueSize", value = "1000")},
            commandProperties = {
                    @HystrixProperty(name = "execution.isolation.thread.timeoutInMilliseconds", value = "100")})
    public Future<QueryProcessResult> executeAsync(QueryProcessRequest request) {
        return new AsyncResult<QueryProcessResult>(){
            @Override
            public QueryProcessResult invoke(){
                return execute(request);
            }
        };
    }

Caused by: java.io.IOException: Class not found
	at org.objectweb.asm.ClassReader.a(Unknown Source)
	at org.objectweb.asm.ClassReader.<init>(Unknown Source)
	at org.objectweb.asm.ClassReader.<init>(Unknown Source)
	at com.netflix.hystrix.contrib.javanica.utils.MethodProvider.unbride(MethodProvider.java:238)
	at com.netflix.hystrix.contrib.javanica.utils.AopUtils.getDeclaredMethod(AopUtils.java:94)

**Comment by dmalch** [comment]
I also experience the same issue, I found out that it happens for generic classes declared in nested jars of a Spring Boot application. The root cause was that the class ClassReader from ASM uses ClassLoader.getSystemResourceAsStream() method, which doesn't see the class file. A possible fix would be to load the class bytes independently and provide them to ClassReader.

**Comment by dmalch** [comment]
Created a PR https://github.com/Netflix/Hystrix/pull/1831
