### ISSUE TITLE
Turbine can not work online, but it is no problem in self-test

### ISSUE THREAD

**Issue by yihaoshi** [Netflix/Hystrix#1887]
myServer_hystrix-turbine_1 | 2018-11-07T14:48:26.693059423Z 2018-11-07 14:48:26.692  INFO 1 --- [           main] o.s.b.a.e.mvc.EndpointHandlerMapping     : Mapped "{[/configprops || /configprops.json],methods=[GET],produces=[application/vnd.spring-boot.actuator.v1+json || application/json]}" onto public java.lang.Object org.springframework.boot.actuate.endpoint.mvc.EndpointMvcAdapter.invoke()
myServer_hystrix-turbine_1 | 2018-11-07T14:48:27.286522842Z 2018-11-07 14:48:27.286  INFO 1 --- [           main] o.s.j.e.a.AnnotationMBeanExporter        : Registering beans for JMX exposure on startup
myServer_hystrix-turbine_1 | 2018-11-07T14:48:27.323505876Z 2018-11-07 14:48:27.323  INFO 1 --- [           main] o.s.j.e.a.AnnotationMBeanExporter        : Bean with name 'configurationPropertiesRebinder' has been autodetected for JMX exposure
myServer_hystrix-turbine_1 | 2018-11-07T14:48:27.324452347Z 2018-11-07 14:48:27.324  INFO 1 --- [           main] o.s.j.e.a.AnnotationMBeanExporter        : Bean with name 'refreshEndpoint' has been autodetected for JMX exposure
myServer_hystrix-turbine_1 | 2018-11-07T14:48:27.325852638Z 2018-11-07 14:48:27.325  INFO 1 --- [           main] o.s.j.e.a.AnnotationMBeanExporter        : Bean with name 'environmentManager' has been autodetected for JMX exposure
myServer_hystrix-turbine_1 | 2018-11-07T14:48:27.334727959Z 2018-11-07 14:48:27.334  INFO 1 --- [           main] o.s.j.e.a.AnnotationMBeanExporter        : Bean with name 'serviceRegistryEndpoint' has been autodetected for JMX exposure
myServer_hystrix-turbine_1 | 2018-11-07T14:48:27.338760128Z 2018-11-07 14:48:27.338  INFO 1 --- [           main] o.s.j.e.a.AnnotationMBeanExporter        : Bean with name 'refreshScope' has been autodetected for JMX exposure
myServer_hystrix-turbine_1 | 2018-11-07T14:48:27.349817504Z 2018-11-07 14:48:27.349  INFO 1 --- [           main] o.s.j.e.a.AnnotationMBeanExporter        : Located managed bean 'environmentManager': registering with JMX server as MBean [org.springframework.cloud.context.environment:name=environmentManager,type=EnvironmentManager]
myServer_hystrix-turbine_1 | 2018-11-07T14:48:27.383733244Z 2018-11-07 14:48:27.383  INFO 1 --- [           main] o.s.j.e.a.AnnotationMBeanExporter        : Located managed bean 'serviceRegistryEndpoint': registering with JMX server as MBean [org.springframework.cloud.client.serviceregistry.endpoint:name=serviceRegistryEndpoint,type=ServiceRegistryEndpoint]
myServer_hystrix-turbine_1 | 2018-11-07T14:48:27.403806857Z 2018-11-07 14:48:27.403  INFO 1 --- [           main] o.s.j.e.a.AnnotationMBeanExporter        : Located managed bean 'refreshScope': registering with JMX server as MBean [org.springframework.cloud.context.scope.refresh:name=refreshScope,type=RefreshScope]
myServer_hystrix-turbine_1 | 2018-11-07T14:48:27.473738975Z 2018-11-07 14:48:27.458  INFO 1 --- [           main] o.s.j.e.a.AnnotationMBeanExporter        : Located managed bean 'configurationPropertiesRebinder': registering with JMX server as MBean [org.springframework.cloud.context.properties:name=configurationPropertiesRebinder,context=224edc67,type=ConfigurationPropertiesRebinder]
myServer_hystrix-turbine_1 | 2018-11-07T14:48:27.524511316Z 2018-11-07 14:48:27.513  INFO 1 --- [           main] o.s.j.e.a.AnnotationMBeanExporter        : Located managed bean 'refreshEndpoint': registering with JMX server as MBean [org.springframework.cloud.endpoint:name=refreshEndpoint,type=RefreshEndpoint]
myServer_hystrix-turbine_1 | 2018-11-07T14:48:27.855003356Z 2018-11-07 14:48:27.853  INFO 1 --- [           main] o.s.c.support.DefaultLifecycleProcessor  : Starting beans in phase 0
myServer_hystrix-turbine_1 | 2018-11-07T14:48:27.884371575Z 2018-11-07 14:48:27.884  INFO 1 --- [           main] o.s.c.n.turbine.SpringAggregatorFactory  : Could not find monitors: []
myServer_hystrix-turbine_1 | 2018-11-07T14:48:28.362561472Z 2018-11-07 14:48:28.362  INFO 1 --- [           main] c.n.t.monitor.cluster.ClusterMonitor     : Registering event handler for cluster monitor: StaticListener_For_Aggregator
myServer_hystrix-turbine_1 | 2018-11-07T14:48:28.364772112Z 2018-11-07 14:48:28.364  INFO 1 --- [           main] c.n.t.handler.TurbineDataDispatcher      : 
myServer_hystrix-turbine_1 | 2018-11-07T14:48:28.364792198Z 
myServer_hystrix-turbine_1 | 2018-11-07T14:48:28.364812595Z Just added and starting handler tuple: StaticListener_For_Aggregator
myServer_hystrix-turbine_1 | 2018-11-07T14:48:28.364832953Z 2018-11-07 14:48:28.364  INFO 1 --- [           main] c.n.t.monitor.cluster.ClusterMonitor     : All event handlers for cluster monitor: [StaticListener_For_Aggregator]
myServer_hystrix-turbine_1 | 2018-11-07T14:48:28.364841200Z 2018-11-07 14:48:28.364  INFO 1 --- [           main] c.n.t.monitor.cluster.ClusterMonitor     : Starting up the cluster monitor for default_agg
myServer_hystrix-turbine_1 | 2018-11-07T14:48:28.388308289Z 2018-11-07 14:48:28.387  INFO 1 --- [           main] c.n.t.discovery.InstanceObservable       : Starting InstanceObservable at frequency: 60000 millis
myServer_hystrix-turbine_1 | 2018-11-07T14:48:28.388691851Z 2018-11-07 14:48:28.388  INFO 1 --- [        Timer-0] o.s.c.n.t.CommonsInstanceDiscovery       : Fetching instance list for apps: [hmi-server, parameter]
myServer_hystrix-turbine_1 | 2018-11-07T14:48:28.388849888Z 2018-11-07 14:48:28.388  INFO 1 --- [        Timer-0] o.s.c.n.t.CommonsInstanceDiscovery       : Fetching instances for app: hmi-server
myServer_hystrix-turbine_1 | 2018-11-07T14:48:28.700600224Z 2018-11-07 14:48:28.699  INFO 1 --- [           main] s.a.ScheduledAnnotationBeanPostProcessor : No TaskScheduler/ScheduledExecutorService bean found for scheduled processing
myServer_hystrix-turbine_1 | 2018-11-07T14:48:28.829167938Z 2018-11-07 14:48:28.828  INFO 1 --- [        Timer-0] o.s.c.n.t.CommonsInstanceDiscovery       : Received instance list for service: hmi-server, size=1
myServer_hystrix-turbine_1 | 2018-11-07T14:48:28.829976529Z 2018-11-07 14:48:28.829  INFO 1 --- [        Timer-0] o.s.c.n.t.CommonsInstanceDiscovery       : Fetching instances for app: parameter
myServer_hystrix-turbine_1 | 2018-11-07T14:48:28.834261240Z 2018-11-07 14:48:28.833  WARN 1 --- [        Timer-0] o.s.c.n.t.CommonsInstanceDiscovery       : DiscoveryClient returned null or empty for service: parameter
myServer_hystrix-turbine_1 | 2018-11-07T14:48:28.834277569Z 2018-11-07 14:48:28.833  INFO 1 --- [        Timer-0] c.n.t.discovery.InstanceObservable       : Retrieved hosts from InstanceDiscovery: 1
myServer_hystrix-turbine_1 | 2018-11-07T14:48:28.834282628Z 2018-11-07 14:48:28.833  INFO 1 --- [        Timer-0] c.n.t.discovery.InstanceObservable       : Found hosts that have been previously terminated: 0
myServer_hystrix-turbine_1 | 2018-11-07T14:48:28.834287373Z 2018-11-07 14:48:28.834  INFO 1 --- [        Timer-0] c.n.t.discovery.InstanceObservable       : Hosts up:1, hosts down: 0
myServer_hystrix-turbine_1 | 2018-11-07T14:48:28.921811702Z 2018-11-07 14:48:28.921  INFO 1 --- [        Timer-0] c.n.t.monitor.instance.InstanceMonitor   : Url for host: http://192.168.35.8:0/hystrix.stream default
myServer_hystrix-turbine_1 | 2018-11-07T14:48:28.929290225Z 2018-11-07 14:48:28.928  INFO 1 --- [        Timer-0] c.n.t.handler.TurbineDataDispatcher      : 
myServer_hystrix-turbine_1 | 2018-11-07T14:48:28.929309895Z 
myServer_hystrix-turbine_1 | 2018-11-07T14:48:28.929314684Z Just added and starting handler tuple: default_agg_aggClusterEventHandler
myServer_hystrix-turbine_1 | 2018-11-07T14:48:28.958489430Z 2018-11-07 14:48:28.957  INFO 1 --- [        Timer-0] c.n.turbine.data.AggDataFromCluster      : Per handler dispacher started for: default_agg_aggClusterEventHandler
myServer_hystrix-turbine_1 | 2018-11-07T14:48:29.011201192Z 2018-11-07 14:48:29.003  INFO 1 --- [           main] s.b.c.e.t.TomcatEmbeddedServletContainer : Tomcat started on port(s): 8031 (http)
myServer_hystrix-turbine_1 | 2018-11-07T14:48:29.096419816Z 2018-11-07 14:48:29.071  INFO 1 --- [           main] o.s.c.c.s.ConsulServiceRegistry          : Registering service with consul: NewService{id='hystrix-turbine-8031', name='hystrix-turbine', tags=[], address='f5ee8c9e759d-myServer-hystrix-turbine-1', port=8031, enableTagOverride=null, check=Check{script='null', interval='3s', ttl='null', http='http://f5ee8c9e759d-myServer-hystrix-turbine-1:8031/health', tcp='null', timeout='null', deregisterCriticalServiceAfter='null', tlsSkipVerify=null, status='null'}, checks=null}
myServer_hystrix-turbine_1 | 2018-11-07T14:48:29.178537731Z 2018-11-07 14:48:29.178  INFO 1 --- [           main] c.taobao.tv.turbine.TurbineApplication   : Started TurbineApplication in 16.738 seconds (JVM running for 17.915)
myServer_hystrix-turbine_1 | 2018-11-07T14:48:31.894019317Z 2018-11-07 14:48:31.893  INFO 1 --- [nio-8031-exec-1] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring FrameworkServlet 'dispatcherServlet'
myServer_hystrix-turbine_1 | 2018-11-07T14:48:31.894440764Z 2018-11-07 14:48:31.894  INFO 1 --- [nio-8031-exec-1] o.s.web.servlet.DispatcherServlet        : FrameworkServlet 'dispatcherServlet': initialization started
myServer_hystrix-turbine_1 | 2018-11-07T14:48:31.929914172Z 2018-11-07 14:48:31.929  INFO 1 --- [nio-8031-exec-1] o.s.web.servlet.DispatcherServlet        : FrameworkServlet 'dispatcherServlet': initialization completed in 35 ms
myServer_hystrix-turbine_1 | 2018-11-07T14:48:39.210936101Z 2018-11-07 14:48:39.209  WARN 1 --- [InstanceMonitor] c.n.t.monitor.instance.InstanceMonitor   : Stopping InstanceMonitor for: 192.168.35.8:0 default
myServer_hystrix-turbine_1 | 2018-11-07T14:48:39.210976835Z 
myServer_hystrix-turbine_1 | 2018-11-07T14:48:39.210982610Z org.apache.http.conn.ConnectTimeoutException: Connect to 192.168.35.8:80 timed out
myServer_hystrix-turbine_1 | 2018-11-07T14:48:39.210987162Z   at org.apache.http.conn.scheme.PlainSocketFactory.connectSocket(PlainSocketFactory.java:123) ~[httpclient-4.5.5.jar!/:4.5.5]
myServer_hystrix-turbine_1 | 2018-11-07T14:48:39.210998487Z   at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:180) ~[httpclient-4.5.5.jar!/:4.5.5]
myServer_hystrix-turbine_1 | 2018-11-07T14:48:39.211003504Z   at org.apache.http.impl.conn.ManagedClientConnectionImpl.open(ManagedClientConnectionImpl.java:326) ~[httpclient-4.5.5.jar!/:4.5.5]
myServer_hystrix-turbine_1 | 2018-11-07T14:48:39.211009558Z   at org.apache.http.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:610) ~[httpclient-4.5.5.jar!/:4.5.5]
myServer_hystrix-turbine_1 | 2018-11-07T14:48:39.211015073Z   at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:445) ~[httpclient-4.5.5.jar!/:4.5.5]
myServer_hystrix-turbine_1 | 2018-11-07T14:48:39.211019840Z   at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:835) ~[httpclient-4.5.5.jar!/:4.5.5]
myServer_hystrix-turbine_1 | 2018-11-07T14:48:39.211023946Z   at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83) ~[httpclient-4.5.5.jar!/:4.5.5]
myServer_hystrix-turbine_1 | 2018-11-07T14:48:39.211028210Z   at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108) ~[httpclient-4.5.5.jar!/:4.5.5]
myServer_hystrix-turbine_1 | 2018-11-07T14:48:39.211032255Z   at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56) ~[httpclient-4.5.5.jar!/:4.5.5]
myServer_hystrix-turbine_1 | 2018-11-07T14:48:39.211048399Z   at com.netflix.turbine.monitor.instance.InstanceMonitor.init(InstanceMonitor.java:307) ~[turbine-core-1.0.0.jar!/:na]
myServer_hystrix-turbine_1 | 2018-11-07T14:48:39.211052813Z   at com.netflix.turbine.monitor.instance.InstanceMonitor.access$100(InstanceMonitor.java:103) ~[turbine-core-1.0.0.jar!/:na]
myServer_hystrix-turbine_1 | 2018-11-07T14:48:39.211057170Z   at com.netflix.turbine.monitor.instance.InstanceMonitor$2.call(InstanceMonitor.java:235) [turbine-core-1.0.0.jar!/:na]
myServer_hystrix-turbine_1 | 2018-11-07T14:48:39.211061148Z   at com.netflix.turbine.monitor.instance.InstanceMonitor$2.call(InstanceMonitor.java:229) [turbine-core-1.0.0.jar!/:na]
myServer_hystrix-turbine_1 | 2018-11-07T14:48:39.211065327Z   at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_181]
myServer_hystrix-turbine_1 | 2018-11-07T14:48:39.211069311Z   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_181]
myServer_hystrix-turbine_1 | 2018-11-07T14:48:39.211074728Z   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_181]
myServer_hystrix-turbine_1 | 2018-11-07T14:48:39.211078948Z   at java.lang.Thread.run(Thread.java:748) [na:1.8.0_181]
myServer_hystrix-turbine_1 | 2018-11-07T14:48:39.211082996Z 
myServer_hystrix-turbine_1 | 2018-11-07T14:48:39.211086565Z 2018-11-07 14:48:39.209  INFO 1 --- [InstanceMonitor] c.n.t.monitor.instance.InstanceMonitor   : Single Server event publisher releasing http client connection for: 192.168.35.8:0 default
myServer_hystrix-turbine_1 | 2018-11-07T14:48:39.211091090Z 2018-11-07 14:48:39.209  INFO 1 --- [InstanceMonitor] c.n.t.m.cluster.AggregateClusterMonitor  : Host lost: 192.168.35.8:0, adding to time based cache
myServer_hystrix-turbine_1 | 2018-11-07T14:48:39.211096721Z 
myServer_hystrix-turbine_1 | 2018-11-07T14:48:39.211100606Z 2018-11-07 14:48:39.210  INFO 1 --- [InstanceMonitor] c.n.t.monitor.instance.InstanceMonitor   : Removing monitor from StatsEventConsole: 192.168.35.8:0 default
myServer_hystrix-turbine_1 | 2018-11-07T14:49:28.389096354Z 2018-11-07 14:49:28.388  INFO 1 --- [        Timer-0] o.s.c.n.t.CommonsInstanceDiscovery       : Fetching instance list for apps: [hmi-server, parameter]
myServer_hystrix-turbine_1 | 2018-11-07T14:49:28.389248094Z 2018-11-07 14:49:28.388  INFO 1 --- [        Timer-0] o.s.c.n.t.CommonsInstanceDiscovery       : Fetching instances for app: hmi-server
myServer_hystrix-turbine_1 | 2018-11-07T14:49:28.393235132Z 2018-11-07 14:49:28.393  INFO 1 --- [        Timer-0] o.s.c.n.t.CommonsInstanceDiscovery       : Received instance list for service: hmi-server, size=1
myServer_hystrix-turbine_1 | 2018-11-07T14:49:28.393459770Z 2018-11-07 14:49:28.393  INFO 1 --- [        Timer-0] o.s.c.n.t.CommonsInstanceDiscovery       : Fetching instances for app: parameter
myServer_hystrix-turbine_1 | 2018-11-07T14:49:28.396256521Z 2018-11-07 14:49:28.396  WARN 1 --- [        Timer-0] o.s.c.n.t.CommonsInstanceDiscovery       : DiscoveryClient returned null or empty for service: parameter
myServer_hystrix-turbine_1 | 2018-11-07T14:49:28.396275427Z 2018-11-07 14:49:28.396  INFO 1 --- [        Timer-0] c.n.t.discovery.InstanceObservable       : Retrieved hosts from InstanceDiscovery: 1
myServer_hystrix-turbine_1 | 2018-11-07T14:49:28.396479463Z 2018-11-07 14:49:28.396  INFO 1 --- [        Timer-0] c.n.t.discovery.InstanceObservable       : Found hosts that have been previously terminated: 0
myServer_hystrix-turbine_1 | 2018-11-07T14:49:28.396490461Z 2018-11-07 14:49:28.396  INFO 1 --- [        Timer-0] c.n.t.discovery.InstanceObservable       : Hosts up:1, hosts down: 0
myServer_hystrix-turbine_1 | 2018-11-07T14:49:28.396641758Z 2018-11-07 14:49:28.396  INFO 1 --- [        Timer-0] c.n.t.monitor.instance.InstanceMonitor   : Url for host: http://192.168.35.8:0/hystrix.stream default
myServer_hystrix-turbine_1 | 2018-11-07T14:49:38.413089136Z 2018-11-07 14:49:38.412  WARN 1 --- [InstanceMonitor] c.n.t.monitor.instance.InstanceMonitor   : Stopping InstanceMonitor for: 192.168.35.8:0 default
myServer_hystrix-turbine_1 | 2018-11-07T14:49:38.413114774Z 
myServer_hystrix-turbine_1 | 2018-11-07T14:49:38.413119632Z org.apache.http.conn.ConnectTimeoutException: Connect to 192.168.35.8:80 timed out
myServer_hystrix-turbine_1 | 2018-11-07T14:49:38.413123505Z   at org.apache.http.conn.scheme.PlainSocketFactory.connectSocket(PlainSocketFactory.java:123) ~[httpclient-4.5.5.jar!/:4.5.5]
myServer_hystrix-turbine_1 | 2018-11-07T14:49:38.413127913Z   at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:180) ~[httpclient-4.5.5.jar!/:4.5.5]
myServer_hystrix-turbine_1 | 2018-11-07T14:49:38.413132368Z   at org.apache.http.impl.conn.ManagedClientConnectionImpl.open(ManagedClientConnectionImpl.java:326) ~[httpclient-4.5.5.jar!/:4.5.5]
myServer_hystrix-turbine_1 | 2018-11-07T14:49:38.413136867Z   at org.apache.http.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:610) ~[httpclient-4.5.5.jar!/:4.5.5]
myServer_hystrix-turbine_1 | 2018-11-07T14:49:38.413141064Z   at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:445) ~[httpclient-4.5.5.jar!/:4.5.5]
myServer_hystrix-turbine_1 | 2018-11-07T14:49:38.413145249Z   at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:835) ~[httpclient-4.5.5.jar!/:4.5.5]
myServer_hystrix-turbine_1 | 2018-11-07T14:49:38.413163576Z   at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83) ~[httpclient-4.5.5.jar!/:4.5.5]
myServer_hystrix-turbine_1 | 2018-11-07T14:49:38.413168447Z   at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108) ~[httpclient-4.5.5.jar!/:4.5.5]
myServer_hystrix-turbine_1 | 2018-11-07T14:49:38.413173099Z   at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56) ~[httpclient-4.5.5.jar!/:4.5.5]
myServer_hystrix-turbine_1 | 2018-11-07T14:49:38.413177483Z   at com.netflix.turbine.monitor.instance.InstanceMonitor.init(InstanceMonitor.java:307) ~[turbine-core-1.0.0.jar!/:na]
myServer_hystrix-turbine_1 | 2018-11-07T14:49:38.413181875Z   at com.netflix.turbine.monitor.instance.InstanceMonitor.access$100(InstanceMonitor.java:103) ~[turbine-core-1.0.0.jar!/:na]
myServer_hystrix-turbine_1 | 2018-11-07T14:49:38.413186145Z   at com.netflix.turbine.monitor.instance.InstanceMonitor$2.call(InstanceMonitor.java:235) [turbine-core-1.0.0.jar!/:na]
myServer_hystrix-turbine_1 | 2018-11-07T14:49:38.413190389Z   at com.netflix.turbine.monitor.instance.InstanceMonitor$2.call(InstanceMonitor.java:229) [turbine-core-1.0.0.jar!/:na]
myServer_hystrix-turbine_1 | 2018-11-07T14:49:38.413194545Z   at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_181]
myServer_hystrix-turbine_1 | 2018-11-07T14:49:38.413198742Z   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_181]
myServer_hystrix-turbine_1 | 2018-11-07T14:49:38.413204319Z   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_181]
myServer_hystrix-turbine_1 | 2018-11-07T14:49:38.413208693Z   at java.lang.Thread.run(Thread.java:748) [na:1.8.0_181]
myServer_hystrix-turbine_1 | 2018-11-07T14:49:38.413212777Z 
myServer_hystrix-turbine_1 | 2018-11-07T14:49:38.413216508Z 2018-11-07 14:49:38.412  INFO 1 --- [InstanceMonitor] c.n.t.monitor.instance.InstanceMonitor   : Single Server event publisher releasing http client connection for: 192.168.35.8:0 default
myServer_hystrix-turbine_1 | 2018-11-07T14:49:38.413241119Z 2018-11-07 14:49:38.412  INFO 1 --- [InstanceMonitor] c.n.t.m.cluster.AggregateClusterMonitor  : Host lost: 192.168.35.8:0, adding to time based cache
myServer_hystrix-turbine_1 | 2018-11-07T14:49:38.413246723Z 
myServer_hystrix-turbine_1 | 2018-11-07T14:49:38.413250254Z 2018-11-07 14:49:38.412  INFO 1 --- [InstanceMonitor] c.n.t.monitor.instance.InstanceMonitor   : Removing monitor from StatsEventConsole: 192.168.35.8:0 default

**Comment by yihaoshi** [comment]
this is my properties 
turbine:
  appConfig: my-server,my-parameter
  clusterNameExpression: "'my-life-prod'"
  combineHostPort: true

**Comment by yihaoshi** [comment]
this is my properties
turbine:
  appConfig: my-server,my-parameter
  cluster-name-expression: metadata['cluster']
  combineHostPort: true
  aggregator:
    clusterConfig: my-life-prod

**Comment by yihaoshi** [comment]
the ip 192.168.35.8 i don't know what is it,i don’t know where is from
