### ISSUE TITLE
hystrix.threadpool.<POOL>.coreSize configuration does not work when increasing

### ISSUE THREAD

**Issue by jogoussard** [Netflix/Hystrix#1897]
Hi
Starting with a configuration as
hystrix.threadpool.MyPool.coreSize=30
and increasing afterwards dynamically to above 30 does not work because HystrixThreadPool sets *first* the core size and *second* the max size (line 230/231). So as the core size we are trying to set is above the current max size, the JVM rejects the call to setCorePoolSize.
The fix seems simply to use:
```
		if (dynamicMaximumSize < dynamicCoreSize) {
				dynamicMaximumSize = dynamicCoreSize;
		}
                threadPool.setMaximumPoolSize(dynamicMaximumSize);
                threadPool.setCorePoolSize(dynamicCoreSize);
```
Exception seen:
```
java.lang.IllegalArgumentException: null
	at java.base/java.util.concurrent.ThreadPoolExecutor.setCorePoolSize(ThreadPoolExecutor.java:1560)
	at com.netflix.hystrix.HystrixThreadPool$HystrixThreadPoolDefault.touchConfig(HystrixThreadPool.java:230)
	at com.netflix.hystrix.HystrixThreadPool$HystrixThreadPoolDefault.getScheduler(HystrixThreadPool.java:205)
```

**Comment by jogoussard** [comment]
Of course, if you agree with the fix, I can take care of the PR.

**Comment by jogoussard** [comment]
Fixed by  https://github.com/Netflix/Hystrix/pull/1877.
