### ISSUE TITLE
Archaius version update?

### ISSUE THREAD

**Issue by samhendley** [Netflix/Hystrix#252]
Hystrix is still tied to version 0.4.1 of the archaius library. Can we update to a newer version? I only noticed because that version doesn't correctly expose it's dependencies. In particular it doesn't list commons-lang in its depdencies which gave me an unexpected runtime error (below).

```
[ERROR][scheduler-3][2014-04-29 08:26:01,901] org.springframework.scheduling.support.TaskUtils$LoggingErrorHandler.handleError(TaskUtils.java:95) - Unexpected error occurred in scheduled task.
java.lang.NoClassDefFoundError: org/apache/commons/lang/text/StrLookup
at com.netflix.config.ConfigurationManager.getConfigInstance(ConfigurationManager.java:125)
at com.netflix.config.DynamicPropertyFactory.getInstance(DynamicPropertyFactory.java:263)
at com.netflix.config.DynamicProperty.getInstance(DynamicProperty.java:245)
at com.netflix.config.PropertyWrapper.<init>(PropertyWrapper.java:58)
at com.netflix.hystrix.strategy.properties.HystrixPropertiesChainedArchaiusProperty$DynamicBooleanProperty.<init>(HystrixPropertiesChainedArchaiusProperty.java:300)
at com.netflix.hystrix.HystrixCommandProperties.getProperty(HystrixCommandProperties.java:384)
at com.netflix.hystrix.HystrixCommandProperties.<init>(HystrixCommandProperties.java:116)
at com.netflix.hystrix.HystrixCommandProperties.<init>(HystrixCommandProperties.java:110)
```

**Comment by mattrjacobs** [comment]
From looking at public interfaces which deal with configuration, I believe a 2.0 release will be required.  I'll start outlining the required changes here.

**Comment by li-a** [comment]
[archaius 0.4.1's dependency specifically on commons-configuration 1.8](http://central.maven.org/maven2/com/netflix/archaius/archaius-core/0.4.1/archaius-core-0.4.1.pom) gets it flagged by some security scans because of its [optional dependency on commons-collections 3.2.1](http://central.maven.org/maven2/commons-configuration/commons-configuration/1.8/commons-configuration-1.8.pom), which has [popular security vulnerabilities](https://www.cvedetails.com/version/187982/Apache-Commons-Collections-3.2.1.html).

Seems like this will get resolved only in a 2.x, but there's so little movement on the project lately.. should I stop holding my breath?
