### ISSUE TITLE
Dashboard gets "Error proxying request" errors when using Turbine

### ISSUE THREAD

**Issue by johanhaleby** [Netflix/Hystrix#267]
We frequently run into errors like this when using Turbine 0.4 and Hystrix 1.3.16. Stacktrace example:

```java
2014-05-21 11:04:50 ERROR  com.netflix.hystrix.dashboard.stream.ProxyStreamServlet:115 [ProxyStreamServlet] [doGet]: Error proxying request: http://xxx.y.com:8080/turbine-web-0.4/turbine.stream?cluster=my-cluster
java.lang.RuntimeException: org.mortbay.jetty.EofException
        at com.netflix.hystrix.dashboard.stream.ProxyStreamServlet.doGet(ProxyStreamServlet.java:109)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
        at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
        at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:390)
        at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
        at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
        at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
        at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:440)
        at org.mortbay.jetty.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:230)
        at org.mortbay.jetty.handler.HandlerCollection.handle(HandlerCollection.java:114)
        at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
        at org.mortbay.jetty.Server.handle(Server.java:326)
        at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
        at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:926)
        at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:549)
        at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:212)
        at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
        at org.mortbay.io.nio.SelectChannelEndPoint.run(SelectChannelEndPoint.java:410)
        at org.mortbay.thread.QueuedThreadPool$PoolThread.run(QueuedThreadPool.java:582)
Caused by: org.mortbay.jetty.EofException
        at org.mortbay.jetty.AbstractGenerator$Output.write(AbstractGenerator.java:603)
        at com.netflix.hystrix.dashboard.stream.ProxyStreamServlet.doGet(ProxyStreamServlet.java:97)
        ... 19 more
```

Is this a bug or why does this happen?

**Comment by mattrjacobs** [comment]
Closing due to age

**Comment by vermapratyush** [comment]
I am getting the same error.
I have a turbine running at port 7979 and when I do "curl <turbine-host>:7979" it works and I get a stream of aggregated data.
However, with the dashboard the request does not complete and it timeout. In browser and in python, urllib.open("...") also does not work.

**Comment by nguyenvantien2009** [comment]
I also have error with http://{domain}:8080/turbine/turbine.stream. 
Hystrix Dashboard can not read this URL.
Please help.

**Comment by 15936909** [comment]
I am getting the same errors，any solution？

2019-12-26 11:09:46.790 ERROR 29064 --- [p1219916644-872] ashboardConfiguration$ProxyStreamServlet : Error proxying request: http://10.47.188.114:6005/bassServer/hystrix.stream

java.lang.RuntimeException: org.eclipse.jetty.io.EofException
