### ISSUE TITLE
Deadlock under "Fallback: Cache via Network" pattern

### ISSUE THREAD

**Issue by wangkang85** [Netflix/Hystrix#352]
This issue happens in the Rx-based hystrix-core jar, which is version 1.4 series.

We are following exactly the same way as "Fallback: Cache via Network" pattern in https://github.com/Netflix/Hystrix/wiki/How-To-Use.

We are using different thread pools for primary and secondary commands.

We see our Tomcat threads completely blocked in some instances. Here is the stacktrace:

"http-0.0.0.0-7101-56" daemon prio=10 tid=0x00007fc836453000 nid=0x1162 waiting on condition [0x00007fc0639b6000]
   java.lang.Thread.State: WAITING (parking)
  at sun.misc.Unsafe.park(Native Method)
  - parking to wait for  <0x00007fc3ba56b0f8> (a java.util.concurrent.CountDownLatch$Sync)
  at java.util.concurrent.locks.LockSupport.park(LockSupport.java:186)
  at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:834)
  at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:994)
  at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1303)
  at java.util.concurrent.CountDownLatch.await(CountDownLatch.java:236)
  at rx.internal.operators.BlockingOperatorToFuture$2.get(BlockingOperatorToFuture.java:105)
  at com.netflix.hystrix.HystrixExecutableBase$1.performBlockingGetWithTimeout(HystrixExecutableBase.java:506)
  at com.netflix.hystrix.HystrixExecutableBase$1.get(HystrixExecutableBase.java:387)
  at com.netflix.hystrix.HystrixExecutableBase.execute(HystrixExecutableBase.java:296)
  at com.netflix.hystrix.HystrixObservableCommand.execute(HystrixObservableCommand.java:50)
  at com.netflix.hystrix.HystrixCommand.execute(HystrixCommand.java:485)
  at com.netflix.gps.isolation.sims.impl.SimsClientQueryImpl.getVideoSims(SimsClientQueryImpl.java:26)
...

**Comment by mattrjacobs** [comment]
@wangkang85 I saw our server get into this state at one point with 1.3.18.  Upgrading to 1.4.0-rc.9 resolved that deadlock.  Can you try 1.4.0 and see if your issue is resolved?

**Comment by mattrjacobs** [comment]
@wangkang85 Any update on if 1.4.x worked for you?

**Comment by wangkang85** [comment]
The issue is gone in the new release 1.4.4. Thanks for fixing it.
