### ISSUE TITLE
NullPointerException occurs when poller pauses in hystrix-metrics-event-stream-1.4.0-RC5.jar

### ISSUE THREAD

**Issue by kbsivacse** [Netflix/Hystrix#381]
Hi,

I'm getting below exception when I try to access /hystrix.stream. Please check and let me know

java.lang.NullPointerException
at com.netflix.hystrix.contrib.metrics.eventstream.HystrixMetricsPoller.pause(HystrixMetricsPoller.java:98)
at com.netflix.hystrix.contrib.metrics.eventstream.HystrixMetricsPoller.shutdown(HystrixMetricsPoller.java:108)
at com.netflix.hystrix.contrib.metrics.eventstream.HystrixMetricsStreamServlet.handleRequest(HystrixMetricsStreamServlet.java:168)
at com.netflix.hystrix.contrib.metrics.eventstream.HystrixMetricsStreamServlet.doGet(HystrixMetricsStreamServlet.java:74)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:621)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:722)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:305)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:225)
at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:169)
at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:472)
at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:168)
at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:98)
at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:927)
at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118)
at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:407)
at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:999)
at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:565)
at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:307)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
at java.lang.Thread.run(Thread.java:744)

**Comment by mattrjacobs** [comment]
@kbsivacse Can you share some more context around this?  This NPE suggests that ```scheduledTask``` in ```HystrixMetricsPoller``` is null and ```running``` is true, which is an invalid state.  That's clearly a bug, so anything you can provide to help me replicate would be appreciated.  Specifically, what methods on ```HystrixMetricsPoller``` are you calling, and at what point in your server lifecycle are you calling them?

**Comment by kbsivacse** [comment]
Thanks for you reply!

I just added "hystrix-metrics-event-stream-1.4.0-RC5.jar" in to my sample web application and added /hystrix.stream access path for the servlet "com.netflix.hystrix.contrib.metrics.eventstream.HystrixMetricsStreamServlet".

When I try to hit the "/hystrix.stream" at the very first time, I'm getting this exception.

Let me know if you are looking for any other information.

**Comment by mattrjacobs** [comment]
Thanks for the clarification @kbsivacse.  I was able to reproduce this when I didn't have a Jackson jar in my web container.  In this case, the MetricsPoller construction resulted in a ```NoClassDefFoundError```, which was uncaught and left ```running = true, scheduledTask = null```.

I'm not sure of what specific exception you might be encountering, so I will add:

1) Safeguard that doesn't leave an inconsistent state - I will set running back to false if an exception is caught during ```HystrixMetricsPoller.start()```.
2) Error reporting, so that you can fix the underlying error
