### ISSUE TITLE
How to prevent "fallback execution rejected" 

### ISSUE THREAD

**Issue by costimuraru** [Netflix/Hystrix#796]
Any idea what might explain the exception below and what could be done to be prevented?
It happened on a web service that had to cope with a high number of requests. It seems that the threads began to die which rendered the service unavailable.

```java
INFO   | jvm 1    | 2015/05/18 13:08:56 | Exception in thread "pool-19-thread-13" com.netflix.hystrix.exception.HystrixRuntimeException: HystrixXXXCommand fallback execution rejected.
INFO   | jvm 1    | 2015/05/18 13:08:56 | 	at com.netflix.hystrix.AbstractCommand.getFallbackOrThrowException(AbstractCommand.java:753)
INFO   | jvm 1    | 2015/05/18 13:08:56 | 	at com.netflix.hystrix.AbstractCommand.access$300(AbstractCommand.java:65)
INFO   | jvm 1    | 2015/05/18 13:08:56 | 	at com.netflix.hystrix.AbstractCommand$9.call(AbstractCommand.java:585)
INFO   | jvm 1    | 2015/05/18 13:08:56 | 	at com.netflix.hystrix.AbstractCommand$9.call(AbstractCommand.java:573)
INFO   | jvm 1    | 2015/05/18 13:08:56 | 	at rx.internal.operators.OperatorOnErrorResumeNextViaFunction$1.onError(OperatorOnErrorResumeNextViaFunction.java:77)
INFO   | jvm 1    | 2015/05/18 13:08:56 | 	at rx.internal.operators.OperatorDoOnEach$1.onError(OperatorDoOnEach.java:70)
INFO   | jvm 1    | 2015/05/18 13:08:56 | 	at rx.internal.operators.OperatorDoOnEach$1.onError(OperatorDoOnEach.java:70)
INFO   | jvm 1    | 2015/05/18 13:08:56 | 	at com.netflix.hystrix.AbstractCommand$HystrixObservableTimeoutOperator$3.onError(AbstractCommand.java:982)
INFO   | jvm 1    | 2015/05/18 13:08:56 | 	at rx.internal.operators.OperatorDoOnEach$1.onError(OperatorDoOnEach.java:70)
INFO   | jvm 1    | 2015/05/18 13:08:56 | 	at rx.internal.operators.OperatorSubscribeOn$1.onError(OperatorSubscribeOn.java:52)
INFO   | jvm 1    | 2015/05/18 13:08:56 | 	at rx.Observable$1.call(Observable.java:152)
INFO   | jvm 1    | 2015/05/18 13:08:56 | 	at rx.Observable$1.call(Observable.java:136)
INFO   | jvm 1    | 2015/05/18 13:08:56 | 	at rx.Observable$1.call(Observable.java:144)
INFO   | jvm 1    | 2015/05/18 13:08:56 | 	at rx.Observable$1.call(Observable.java:136)
INFO   | jvm 1    | 2015/05/18 13:08:56 | 	at rx.Observable$1.call(Observable.java:144)
INFO   | jvm 1    | 2015/05/18 13:08:56 | 	at rx.Observable$1.call(Observable.java:136)
INFO   | jvm 1    | 2015/05/18 13:08:56 | 	at rx.Observable$1.call(Observable.java:144)
INFO   | jvm 1    | 2015/05/18 13:08:56 | 	at rx.Observable$1.call(Observable.java:136)
INFO   | jvm 1    | 2015/05/18 13:08:56 | 	at rx.Observable$1.call(Observable.java:144)
INFO   | jvm 1    | 2015/05/18 13:08:56 | 	at rx.Observable$1.call(Observable.java:136)
INFO   | jvm 1    | 2015/05/18 13:08:56 | 	at rx.Observable$1.call(Observable.java:144)
INFO   | jvm 1    | 2015/05/18 13:08:56 | 	at rx.Observable$1.call(Observable.java:136)
INFO   | jvm 1    | 2015/05/18 13:08:56 | 	at rx.Observable$1.call(Observable.java:144)
INFO   | jvm 1    | 2015/05/18 13:08:56 | 	at rx.Observable$1.call(Observable.java:136)
INFO   | jvm 1    | 2015/05/18 13:08:56 | 	at rx.Observable$1.call(Observable.java:144)
INFO   | jvm 1    | 2015/05/18 13:08:56 | 	at rx.Observable$1.call(Observable.java:136)
INFO   | jvm 1    | 2015/05/18 13:08:56 | 	at rx.Observable$1.call(Observable.java:144)
INFO   | jvm 1    | 2015/05/18 13:08:56 | 	at rx.Observable$1.call(Observable.java:136)
INFO   | jvm 1    | 2015/05/18 13:08:56 | 	at rx.Observable$1.call(Observable.java:144)
INFO   | jvm 1    | 2015/05/18 13:08:56 | 	at rx.Observable$1.call(Observable.java:136)
INFO   | jvm 1    | 2015/05/18 13:08:56 | 	at rx.Observable.unsafeSubscribe(Observable.java:7495)
INFO   | jvm 1    | 2015/05/18 13:08:56 | 	at com.netflix.hystrix.AbstractCommand$1.call(AbstractCommand.java:393)
INFO   | jvm 1    | 2015/05/18 13:08:56 | 	at com.netflix.hystrix.AbstractCommand$1.call(AbstractCommand.java:373)
INFO   | jvm 1    | 2015/05/18 13:08:56 | 	at rx.Observable$1.call(Observable.java:144)
INFO   | jvm 1    | 2015/05/18 13:08:56 | 	at rx.Observable$1.call(Observable.java:136)
INFO   | jvm 1    | 2015/05/18 13:08:56 | 	at rx.Observable$1.call(Observable.java:144)
INFO   | jvm 1    | 2015/05/18 13:08:56 | 	at rx.Observable$1.call(Observable.java:136)
INFO   | jvm 1    | 2015/05/18 13:08:56 | 	at rx.Observable$1.call(Observable.java:144)
INFO   | jvm 1    | 2015/05/18 13:08:56 | 	at rx.Observable$1.call(Observable.java:136)
INFO   | jvm 1    | 2015/05/18 13:08:56 | 	at rx.Observable.unsafeSubscribe(Observable.java:7495)
INFO   | jvm 1    | 2015/05/18 13:08:56 | 	at com.netflix.hystrix.AbstractCommand$ObservableCommand$1.call(AbstractCommand.java:1110)
INFO   | jvm 1    | 2015/05/18 13:08:56 | 	at com.netflix.hystrix.AbstractCommand$ObservableCommand$1.call(AbstractCommand.java:1106)
INFO   | jvm 1    | 2015/05/18 13:08:56 | 	at rx.Observable$1.call(Observable.java:144)
INFO   | jvm 1    | 2015/05/18 13:08:56 | 	at rx.Observable$1.call(Observable.java:136)
INFO   | jvm 1    | 2015/05/18 13:08:56 | 	at rx.Observable.subscribe(Observable.java:7585)
INFO   | jvm 1    | 2015/05/18 13:08:56 | 	at rx.internal.operators.BlockingOperatorToFuture.toFuture(BlockingOperatorToFuture.java:57)
INFO   | jvm 1    | 2015/05/18 13:08:56 | 	at rx.observables.BlockingObservable.toFuture(BlockingObservable.java:410)
INFO   | jvm 1    | 2015/05/18 13:08:56 | 	at com.netflix.hystrix.HystrixCommand.queue(HystrixCommand.java:379)
INFO   | jvm 1    | 2015/05/18 13:08:56 | 	at com.ph.CassandraExecutor.executeSyncWithTimeout(CassandraExecutor.java:69)
INFO   | jvm 1    | 2015/05/18 13:08:56 | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
INFO   | jvm 1    | 2015/05/18 13:08:56 | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
INFO   | jvm 1    | 2015/05/18 13:08:56 | 	at java.lang.Thread.run(Thread.java:745)
```

**Comment by mattrjacobs** [comment]
As described in the Wiki (https://github.com/Netflix/Hystrix/wiki/How-it-Works#semaphores), Hystrix uses a semaphore on the number of concurrent fallbacks that may be in flight at any point in time.  It must do this so that latency on the fallback path is able to be controlled, especially since fallbacks may run on the calling thread.

Your options for not encountering this situtation:
1) Trigger the fallback path less frequently (fail the command less often)
2) Make the fallback path less expensive/latent
3) Reconfigure the fallback semaphore : https://github.com/Netflix/Hystrix/wiki/Configuration#fallback.isolation.semaphore.maxConcurrentRequests (Note that this may affect the resiliency/stability of your system if you increase this too much)

**Comment by mattrjacobs** [comment]
Closing due to inactivity.  Please re-open if there are any further questions.

**Comment by liaomengge** [comment]
i also have the problem, the i restart my application, then the same problem will occur，after the problem wouldn't occur

`com.netflix.hystrix.exception.HystrixRuntimeException: ping_0 fallback execution rejected.
	at com.netflix.hystrix.AbstractCommand.handleFallbackRejectionByEmittingError(AbstractCommand.java:1029) ~[hystrix-core-1.5.8.jar:1.5.8]
	at com.netflix.hystrix.AbstractCommand.getFallbackOrThrowException(AbstractCommand.java:861) ~[hystrix-core-1.5.8.jar:1.5.8]
	at com.netflix.hystrix.AbstractCommand.handleThreadPoolRejectionViaFallback(AbstractCommand.java:979) ~[hystrix-core-1.5.8.jar:1.5.8]
	at com.netflix.hystrix.AbstractCommand.access$400(AbstractCommand.java:59) ~[hystrix-core-1.5.8.jar:1.5.8]
	at com.netflix.hystrix.AbstractCommand$12.call(AbstractCommand.java:596) ~[hystrix-core-1.5.8.jar:1.5.8]
	at com.netflix.hystrix.AbstractCommand$12.call(AbstractCommand.java:590) ~[hystrix-core-1.5.8.jar:1.5.8]
	at rx.internal.operators.OperatorOnErrorResumeNextViaFunction$4.onError(OperatorOnErrorResumeNextViaFunction.java:140) ~[rxjava-1.2.0.jar:1.2.0]
	at rx.internal.operators.OnSubscribeDoOnEach$DoOnEachSubscriber.onError(OnSubscribeDoOnEach.java:87) ~[rxjava-1.2.0.jar:1.2.0]
	at rx.internal.operators.OnSubscribeDoOnEach$DoOnEachSubscriber.onError(OnSubscribeDoOnEach.java:87) ~[rxjava-1.2.0.jar:1.2.0]
	at com.netflix.hystrix.AbstractCommand$HystrixObservableTimeoutOperator$3.onError(AbstractCommand.java:1176) ~[hystrix-core-1.5.8.jar:1.5.8]
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:54) ~[rxjava-1.2.0.jar:1.2.0]
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30) ~[rxjava-1.2.0.jar:1.2.0]
	at rx.Observable.unsafeSubscribe(Observable.java:10151) ~[rxjava-1.2.0.jar:1.2.0]
	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41) ~[rxjava-1.2.0.jar:1.2.0]
	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30) ~[rxjava-1.2.0.jar:1.2.0]
	at rx.Observable.unsafeSubscribe(Observable.java:10151) ~[rxjava-1.2.0.jar:1.2.0]
	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41) ~[rxjava-1.2.0.jar:1.2.0]
	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30) ~[rxjava-1.2.0.jar:1.2.0]
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48) ~[rxjava-1.2.0.jar:1.2.0]
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30) ~[rxjava-1.2.0.jar:1.2.0]
	at rx.Observable.unsafeSubscribe(Observable.java:10151) ~[rxjava-1.2.0.jar:1.2.0]
	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41) ~[rxjava-1.2.0.jar:1.2.0]
	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30) ~[rxjava-1.2.0.jar:1.2.0]
	at rx.Observable.unsafeSubscribe(Observable.java:10151) ~[rxjava-1.2.0.jar:1.2.0]
	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41) ~[rxjava-1.2.0.jar:1.2.0]
	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30) ~[rxjava-1.2.0.jar:1.2.0]
	at rx.Observable.unsafeSubscribe(Observable.java:10151) ~[rxjava-1.2.0.jar:1.2.0]
	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41) ~[rxjava-1.2.0.jar:1.2.0]
	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30) ~[rxjava-1.2.0.jar:1.2.0]
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48) ~[rxjava-1.2.0.jar:1.2.0]
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30) ~[rxjava-1.2.0.jar:1.2.0]
	at rx.Observable.unsafeSubscribe(Observable.java:10151) ~[rxjava-1.2.0.jar:1.2.0]
	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:51) ~[rxjava-1.2.0.jar:1.2.0]
	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:35) ~[rxjava-1.2.0.jar:1.2.0]
	at rx.Observable.unsafeSubscribe(Observable.java:10151) ~[rxjava-1.2.0.jar:1.2.0]
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48) ~[rxjava-1.2.0.jar:1.2.0]
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33) ~[rxjava-1.2.0.jar:1.2.0]
	at rx.Observable.unsafeSubscribe(Observable.java:10151) ~[rxjava-1.2.0.jar:1.2.0]
	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41) ~[rxjava-1.2.0.jar:1.2.0]
	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30) ~[rxjava-1.2.0.jar:1.2.0]
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48) ~[rxjava-1.2.0.jar:1.2.0]
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30) ~[rxjava-1.2.0.jar:1.2.0]
	at rx.Observable.unsafeSubscribe(Observable.java:10151) ~[rxjava-1.2.0.jar:1.2.0]
	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41) ~[rxjava-1.2.0.jar:1.2.0]
	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30) ~[rxjava-1.2.0.jar:1.2.0]
	at rx.Observable.unsafeSubscribe(Observable.java:10151) ~[rxjava-1.2.0.jar:1.2.0]
	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:51) ~[rxjava-1.2.0.jar:1.2.0]
	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:35) ~[rxjava-1.2.0.jar:1.2.0]
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48) ~[rxjava-1.2.0.jar:1.2.0]
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30) ~[rxjava-1.2.0.jar:1.2.0]
	at rx.Observable.subscribe(Observable.java:10247) ~[rxjava-1.2.0.jar:1.2.0]
	at rx.Observable.subscribe(Observable.java:10214) ~[rxjava-1.2.0.jar:1.2.0]
	at rx.internal.operators.BlockingOperatorToFuture.toFuture(BlockingOperatorToFuture.java:51) ~[rxjava-1.2.0.jar:1.2.0]
	at rx.observables.BlockingObservable.toFuture(BlockingObservable.java:411) ~[rxjava-1.2.0.jar:1.2.0]
	at com.netflix.hystrix.HystrixCommand.queue(HystrixCommand.java:377) ~[hystrix-core-1.5.8.jar:1.5.8]
	at com.netflix.hystrix.HystrixCommand.execute(HystrixCommand.java:343) ~[hystrix-core-1.5.8.jar:1.5.8]`

**Comment by mattrjacobs** [comment]
My comment above still applies.  This behavior is part of Hystrix's protection.

**Comment by falseor** [comment]
I set  circuitBreaker.forceOpen true  then occur this  bug

**Comment by Aparna-SAP** [comment]
Hi ,

  I'm new to using hystrix.. I have enabled fallback for my command and have also used the property 
fallback.isolation.semaphore.maxConcurrentRequests ..

I have also moved to the latest hystrix libraries... Can you please advice what could be the issue here..
I see that there are some queue rejection error which could be because im running multiple concurrent request.. But my backend is pretty fast .. But I see lot of these errors in the logs


#na#	at java.lang.Thread.run(Thread.java:808) |
2018 06 02 08:17:34#+00#ERROR#java.lang.Throwable##anonymous#https-jsse-nio-8041-exec-144#na#wccdf3734#test123#web#wccdf3734#na#na#na#na#com.netflix.hystrix.exception.HystrixRuntimeException: wccdf3734-aa fallback execution rejected. |
2018 06 02 08:17:34#+00#ERROR#java.lang.Throwable##anonymous#https-jsse-nio-8041-exec-144#na#wccdf3734#test123#web#wccdf3734#na#na#na#na#	at com.netflix.hystrix.AbstractCommand.handleFallbackRejectionByEmittingError(AbstractCommand.java:1043) |
2018 06 02 08:17:34#+00#ERROR#java.lang.Throwable##anonymous#https-jsse-nio-8041-exec-144#na#wccdf3734#test123#web#wccdf3734#na#na#na#na#	at com.netflix.hystrix.AbstractCommand.getFallbackOrThrowException(AbstractCommand.java:875) |
2018 06 02 08:17:34#+00#ERROR#java.lang.Throwable##anonymous#https-jsse-nio-8041-exec-144#na#wccdf3734#test123#web#wccdf3734#na#na#na#na#	at com.netflix.hystrix.AbstractCommand.handleThreadPoolRejectionViaFallback(AbstractCommand.java:993) |
2018 06 02 08:17:34#+00#ERROR#java.lang.Throwable##anonymous#https-jsse-nio-8041-exec-144#na#wccdf3734#test123#web#wccdf3734#na#na#na#na#	at com.netflix.hystrix.AbstractCommand.access$400(AbstractCommand.java:60) |
2018 06 02 08:17:34#+00#ERROR#java.lang.Throwable##anonymous#https-jsse-nio-8041-exec-144#na#wccdf3734#test123#web#wccdf3734#na#na#na#na#	at com.netflix.hystrix.AbstractCommand$12.call(AbstractCommand.java:608) |
2018 06 02 08:17:34#+00#ERROR#java.lang.Throwable##anonymous#https-jsse-nio-8041-exec-144#na#wccdf3734#test123#web#wccdf3734#na#na#na#na#	at com.netflix.hystrix.AbstractCommand$12.call(AbstractCommand.java:601) |
2018 06 02 08:17:34#+00#ERROR#java.lang.Throwable##anonymous#https-jsse-nio-8041-exec-144#na#wccdf3734#test123#web#wccdf3734#na#na#na#na#	at rx.internal.operators.OperatorOnErrorResumeNextViaFunction$1.onError(OperatorOnErrorResumeNextViaFunction.java:77) |
2018 06 02 08:17:34#+00#ERROR#java.lang.Throwable##anonymous#https-jsse-nio-8041-exec-144#na#wccdf3734#test123#web#wccdf3734#na#na#na#na#	at rx.internal.operators.OperatorDoOnEach$1.onError(OperatorDoOnEach.java:70) |
2018 06 02 08:17:34#+00#ERROR#java.lang.Throwable##anonymous#https-jsse-nio-8041-exec-144#na#wccdf3734#test123#web#wccdf3734#na#na#na#na#	at rx.internal.operators.OperatorDoOnEach$1.onError(OperatorDoOnEach.java:70) |
2018 06 02 08:17:34#+00#ERROR#java.lang.Throwable##anonymous#https-jsse-nio-8041-exec-144#na#wccdf3734#test123#web#wccdf3734#na#na#na#na#	at com.netflix.hystrix.AbstractCommand$HystrixObservableTimeoutOperator$2.onError(AbstractCommand.java:1194) |

Please advice ..

Thanks,
Aparna
