### ISSUE TITLE
HystrixMetricsStreamServlet IO Exceptions in application logs 

### ISSUE THREAD

**Issue by mcacker** [Netflix/Hystrix#807]
Hi, we're running an application using Hystrix (the latest version, 1.4.10), a Turbine aggregator and the Hystix dashboard.  In the application logs we consistently see:

	2015-06-04 10:27:36,882 [http-nio-8080-exec-4] INFO  [HystrixMetricsPoller.pause() 99] - Stopping the HystrixMetricsPoller
	2015-06-04 10:27:36,882 [http-nio-8080-exec-4] DEBUG [HystrixMetricsStreamServlet.handleRequest() 182] - IOException while trying to write (generally caused by client disconnecting). Will stop polling.
	org.apache.catalina.connector.ClientAbortException: java.io.IOException: Broken pipe
			at org.apache.catalina.connector.OutputBuffer.realWriteBytes(OutputBuffer.java:393)
			at org.apache.tomcat.util.buf.ByteChunk.flushBuffer(ByteChunk.java:426)
			at org.apache.catalina.connector.OutputBuffer.doFlush(OutputBuffer.java:342)
			at org.apache.catalina.connector.OutputBuffer.flush(OutputBuffer.java:317)
			at org.apache.catalina.connector.Response.flushBuffer(Response.java:510)
			at org.apache.catalina.connector.ResponseFacade.flushBuffer(ResponseFacade.java:318)
			at com.netflix.hystrix.contrib.metrics.eventstream.HystrixMetricsStreamServlet.handleRequest(HystrixMetricsStreamServlet.java:165)
			at com.netflix.hystrix.contrib.metrics.eventstream.HystrixMetricsStreamServlet.doGet(HystrixMetricsStreamServlet.java:90)
			at javax.servlet.http.HttpServlet.service(HttpServlet.java:618)
			at javax.servlet.http.HttpServlet.service(HttpServlet.java:725)
			at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291)
			at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
			at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
			at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
			at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
			at com.netflix.hystrix.contrib.requestservlet.HystrixRequestLogViaResponseHeaderServletFilter.doFilter(HystrixRequestLogViaResponseHeaderServletFilter.java:63)
			at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
			at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
			at com.netflix.hystrix.contrib.requestservlet.HystrixRequestContextServletFilter.doFilter(HystrixRequestContextServletFilter.java:53)
			at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
			at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
			at org.jboss.resteasy.plugins.server.servlet.FilterDispatcher.doFilter(FilterDispatcher.java:63)
			at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
			at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
			at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219)
			at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
			at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:501)
			at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142)
			at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
			at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:610)
			at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
			at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:537)
			at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1085)
			at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:658)
			at org.apache.coyote.http11.Http11NioProtocol$Http11ConnectionHandler.process(Http11NioProtocol.java:222)
			at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1556)
			at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1513)
			at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
			at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
			at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
			at java.lang.Thread.run(Thread.java:745)
	Caused by: java.io.IOException: Broken pipe
			at sun.nio.ch.FileDispatcherImpl.write0(Native Method)
			at sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:47)
			at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:93)
			at sun.nio.ch.IOUtil.write(IOUtil.java:65)
			at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:470)
			at org.apache.tomcat.util.net.NioChannel.write(NioChannel.java:127)
			at org.apache.tomcat.util.net.NioBlockingSelector.write(NioBlockingSelector.java:101)
			at org.apache.tomcat.util.net.NioSelectorPool.write(NioSelectorPool.java:173)
			at org.apache.coyote.http11.InternalNioOutputBuffer.writeToSocket(InternalNioOutputBuffer.java:139)
			at org.apache.coyote.http11.InternalNioOutputBuffer.addToBB(InternalNioOutputBuffer.java:197)
			at org.apache.coyote.http11.InternalNioOutputBuffer.access$000(InternalNioOutputBuffer.java:41)
			at org.apache.coyote.http11.InternalNioOutputBuffer$SocketOutputBuffer.doWrite(InternalNioOutputBuffer.java:320)
			at org.apache.coyote.http11.filters.ChunkedOutputFilter.doWrite(ChunkedOutputFilter.java:116)
			at org.apache.coyote.http11.AbstractOutputBuffer.doWrite(AbstractOutputBuffer.java:256)
			at org.apache.coyote.Response.doWrite(Response.java:503)
			at org.apache.catalina.connector.OutputBuffer.realWriteBytes(OutputBuffer.java:388)
			... 40 more
	2015-06-04 10:27:36,882 [http-nio-8080-exec-4] DEBUG [HystrixMetricsStreamServlet.handleRequest() 187] - Stopping Turbine stream to connection

The dashboard appears to work fine.

Before we just upgraded to the latest version of hystrix from 1.3.13, we were also seeing these exceptions, however, in the Tomcat logs we were also seeing continuous turbine exceptions, which have now gone:

	2015-05-22 19:36:09 INFO  com.netflix.turbine.monitor.cluster.ClusterMonitor:232 [ClusterMonitor] [registerListenertoClusterMonitor]: Registering event handler for cluster monitor: StreamingHandler_716d3e3f-d252-47c7-ba7c-59ba2bce0a10
	2015-05-22 19:36:09 INFO  com.netflix.turbine.handler.TurbineDataDispatcher:176 [TurbineDataDispatcher] [getHandlerQueueTuple]:

	Just added and starting handler tuple: StreamingHandler_716d3e3f-d252-47c7-ba7c-59ba2bce0a10
	2015-05-22 19:36:09 INFO  com.netflix.turbine.handler.HandlerQueueTuple$PerHandlerDispatcher:229 [HandlerQueueTuple$PerHandlerDispatcher] [init]: Per handler dispacher started for: StreamingHandler_716d3e3f-d252-47c7-ba7c-59ba2bce0a10
	2015-05-22 19:36:09 INFO  com.netflix.turbine.monitor.cluster.ClusterMonitor:234 [ClusterMonitor] [registerListenertoClusterMonitor]: All event handlers for cluster monitor: [StaticListener_For_Aggregator, StreamingHandler_716d3e3f-d252-47c7-ba7c-59ba2bce0a10]
	2015-05-22 19:36:09 INFO  com.netflix.turbine.monitor.cluster.ClusterMonitor:149 [ClusterMonitor] [startMonitor]: Starting up the cluster monitor for dev_agg
	2015-05-22 19:36:12 INFO  com.netflix.turbine.streaming.servlet.TurbineStreamServlet:137 [TurbineStreamServlet] [streamFromCluster]:

	RETURNING FROM waitOnConnection: StreamingHandler_716d3e3f-d252-47c7-ba7c-59ba2bce0a10
	2015-05-22 19:36:12 INFO  com.netflix.turbine.handler.TurbineDataDispatcher:193 [TurbineDataDispatcher] [deregisterEventHandler]: Removing event handler: StreamingHandler_716d3e3f-d252-47c7-ba7c-59ba2bce0a10
	2015-05-22 19:36:12 INFO  com.netflix.turbine.utils.WorkerThread$1:156 [WorkerThread$1] [call]: Worker got interrupted, shutting down
	2015-05-22 19:36:12 INFO  com.netflix.turbine.handler.HandlerQueueTuple:132 [HandlerQueueTuple] [stop]:

	Removing tuple for : StreamingHandler_716d3e3f-d252-47c7-ba7c-59ba2bce0a10 tuple running: false
	2015-05-22 19:36:12 INFO  com.netflix.turbine.handler.TurbineDataDispatcher:200 [TurbineDataDispatcher] [deregisterEventHandler]:  tuples : [StaticListener_For_Aggregator]
	2015-05-22 19:36:12 INFO  com.netflix.turbine.handler.TurbineDataDispatcher:201 [TurbineDataDispatcher] [deregisterEventHandler]: Removed handler queue tuple for handler: HandlerQueueTuple [eventHandler=com.netflix.turbine.streaming.TurbineStreamingConnection@10a2e4cc]
	2015-05-22 19:36:13 INFO  com.netflix.turbine.discovery.InstanceObservable$1:260 [InstanceObservable$1] [run]: Rertieved hosts from InstanceDiscovery: 2
	2015-05-22 19:36:13 INFO  com.netflix.turbine.discovery.InstanceObservable$1:272 [InstanceObservable$1] [run]: Found hosts that have been previously terminated: 0
	2015-05-22 19:36:13 INFO  com.netflix.turbine.discovery.InstanceObservable$1:289 [InstanceObservable$1] [run]: Hosts up:2, hosts down: 0
	2015-05-22 19:36:18 INFO  com.netflix.turbine.streaming.servlet.TurbineStreamServlet:79 [TurbineStreamServlet] [doGet]: FilterCriteria: []
	2015-05-22 19:36:18 INFO  com.netflix.turbine.streaming.servlet.TurbineStreamServlet:81 [TurbineStreamServlet] [doGet]: StatsType filters: []
	2015-05-22 19:36:18 INFO  com.netflix.turbine.streaming.TurbineStreamingConnection:153 [TurbineStreamingConnection] [<init>]: Relevance config: []
	2015-05-22 19:36:18 INFO  com.netflix.turbine.streaming.TurbineStreamingConnection:157 [TurbineStreamingConnection] [<init>]: Relevance metrics config: {}

thanks, Mitchell

**Comment by mcacker** [comment]
Duh, it's DEBUG level logging.  Not sure if it used to be, but switching logging level to com.netflix to WARN
