### ISSUE TITLE
Hung HystrixMetricsStreamServlet threads

### ISSUE THREAD

**Issue by genshapiro** [Netflix/Hystrix#821]
We are seeing a number of these errors (see below) in version 1.3.18. 

It appears to be related to https://github.com/Netflix/Hystrix/pull/530. 
What is your recommndation?

00000068 ThreadMonitor W   WSVR0605W: Thread "WebContainer : 2" (00000095) has been active for 686979 milliseconds and may be hung.  There is/are 1 thread(s) in total in the server that may be hung.
        at java.lang.Thread.sleep(Native Method)
        at java.lang.Thread.sleep(Thread.java:897)
        at com.netflix.hystrix.contrib.metrics.eventstream.HystrixMetricsStreamServlet.handleRequest(HystrixMetricsStreamServlet.java:151)
        at com.netflix.hystrix.contrib.metrics.eventstream.HystrixMetricsStreamServlet.doGet(HystrixMetricsStreamServlet.java:74)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:575)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:668)
        at com.ibm.ws.webcontainer.servlet.ServletWrapper.service(ServletWrapper.java:1230)

**Comment by jboyd01** [comment]
This message is a warning from the WebSphere hung thread detection
subsystem.  WebSphere is reporting that this request is taking longer then
expected to finish.  "Normal" servlet threads perform a function and return
to the free pool relatively quickly under "normal" circumstances.  This
thread is running the Hystrix Metrics Stream Servlet which is a never
ending loop that returns data to the client, sleeps and then repeats the
process until the app or server is shutdown or the client disconnects.  If
the client disconnects the Metrics Stream Servlet will detect this, quit
the loop and the thread will be returned back to the free thread pool.  The
message is a warning only and should actually be expected on long running
tasks.  See
https://www.ibm.com/developerworks/community/blogs/aimsupport/entry/hung_thread_detection_in_websphere_application_server
for more details on hung thread detection.

- Jay

**Comment by dsukner** [comment]
As part of pull request #530 enhance client disconnect detection seems to have been added for WebSphere. Would it prevent this warning in the first place? 
https://github.com/jboyd01/Hystrix/commit/223b1ead93de237154a86d09d0c540c41cb8f998

**Comment by jboyd01** [comment]
Not really.  Pull #530 only makes the servlet realize the client disconnected and then terminate the loop.  If any request takes longer then the configured threshold (default is 10 minutes) WebSphere will report it as potentially hung.  You can [change some hung thread detection parameters] (http://www-01.ibm.com/support/knowledgecenter/SSAW57_8.0.0/com.ibm.websphere.nd.doc/info/ae/ae/ttrb_confighangdet.html) but its system wide and you probably just want to ignore any hangs reported for the HystrixMetricsStreamServlet.

**Comment by dsukner** [comment]
Thanks Jay. In our case we use turbine to poll the servlet on our jvms is
there any reason that a poll would take 12 minutes? Is that an indication
of a possible issue?

**Comment by mattrjacobs** [comment]
Closing due to inactivity.  Please re-open if there's more to discuss
