### ISSUE TITLE
@CacheResult on @HystrixCommand causes a NPE

### ISSUE THREAD

**Issue by AlexejK** [Netflix/Hystrix#995]
Hi,

I'm hitting a bit of a confusing issue when trying to use request caching with Hystrix Command.
The `@HystrixCommand` without `@CacheResult` annotation works perfectly fine, however as soon as I add the annotation, it fails with a NullPointerException.

```
Caused by: java.lang.NullPointerException: null
	at com.netflix.hystrix.HystrixRequestCache.get(HystrixRequestCache.java:104) ~[hystrix-core-1.4.20.jar:1.4.20]
	at com.netflix.hystrix.AbstractCommand.toObservable(AbstractCommand.java:346) ~[hystrix-core-1.4.20.jar:1.4.20]
	at com.netflix.hystrix.HystrixCommand.toObservable(HystrixCommand.java:42) ~[hystrix-core-1.4.20.jar:1.4.20]
	at com.netflix.hystrix.HystrixCommand.queue(HystrixCommand.java:378) ~[hystrix-core-1.4.20.jar:1.4.20]
	at com.netflix.hystrix.HystrixCommand.execute(HystrixCommand.java:335) ~[hystrix-core-1.4.20.jar:1.4.20]
```

The HystrixCommand takes one argument, which is a string, CacheKey is being detected properly but for some reason I'm always getting this NPE.

**Comment by dmgcodevil** [comment]
will try with last javanica version. 1.4.20 still uses bogus ObservableResult

**Comment by AlexejK** [comment]
Well this was my fault to begin with: I did not really initialise the `HystrixRequestContext` as described here: https://netflix.github.io/Hystrix/javadoc/com/netflix/hystrix/strategy/concurrency/HystrixRequestContext.html
I Assume this is still needed even when using Javanica.

However, NPE should not be happening. In Hystrix 1.4.18 I was actually able to get an exception clearly stating that `HystrixRequestContext.initializeContext()`has to be called first.

**Comment by dmgcodevil** [comment]
yes, context must be initialized as with venila hystrix.

**Comment by AlexejK** [comment]
So I guess we can conclude that there is simply a problem of an NPE being cast instead of the exception that was given pre 1.4.20 that notified about `HystrixRequestContext.initializeContext()`.
